package locators;

import java.util.Map;

import commonMethods.Testcases;
import commonMethods.Utils;

public interface CAR_Approval_Locators{

	Map<String, String> ExcelData = Utils.getDataAsMap(Testcases.conection_vale, "CAR_Approval", "Reference_Name", Testcases.environmentName);

	public static String UserName_Filter_Input_UCA = ExcelData.get("UserName_Filter_Input_UCA");
	public static String Approval_LimitTable_UCA = ExcelData.get("Approval_LimitTable_UCA");
	public static String Remarks_Input = ExcelData.get("Remarks_Input");
	public static String Remark_Ok = ExcelData.get("Remark_Ok");
	public static String CAR_Terminal_Search = ExcelData.get("CAR_Terminal_Search");
	public static String ToBeReported = ExcelData.get("ToBeReported");
	public static String CAR_Norecords = ExcelData.get("CAR_Norecords");
	public static String Attachment_Download = ExcelData.get("Attachment_Download");
	public static String Vendor_TreeTable = ExcelData.get("Vendor_TreeTable");
	public static String CAR_Terminal_Input = ExcelData.get("CAR_Terminal_Input");
	public static String MainActivityFilter = ExcelData.get("MainActivityFilter");
	public static String CAR_Remarks_Input = ExcelData.get("CAR_Remarks_Input");
	public static String CAR_Remark_Ok = ExcelData.get("CAR_Remark_Ok");
	public static String ServiceTax_Filter = ExcelData.get("ServiceTax_Filter");
	public static String ActivityCode_Filter = ExcelData.get("ActivityCode_Filter");
	public static String PercentageInput = ExcelData.get("PercentageInput");
	public static String Approved_Conditionfilter = ExcelData.get("Approved_Conditionfilter");
	public static String ContractNo_filter = ExcelData.get("ContractNo_filter");
	public static String Predictable_Quantity = ExcelData.get("Predictable_Quantity");
	public static String UnPredictable_Filter = ExcelData.get("UnPredictable_Filter");
	public static String RejectExpense = ExcelData.get("RejectExpense");
	public static String Total_ApprovedCost = ExcelData.get("Total_ApprovedCost");
	public static String UnPredictable_Quantity = ExcelData.get("UnPredictable_Quantity");
	public static String UnPredictable_TotalCost = ExcelData.get("UnPredictable_TotalCost");
	public static String UnPredictable_ChargeRate = ExcelData.get("UnPredictable_ChargeRate");
	public static String Approved_quantity = ExcelData.get("Approved_quantity");
	public static String Approved_TotalCost = ExcelData.get("Approved_TotalCost");
	public static String ActivityName_filter = ExcelData.get("ActivityName_filter");
	public static String Approved_Filter = ExcelData.get("Approved_Filter");
	public static String Predictable_TotalCost = ExcelData.get("Predictable_TotalCost");
	public static String Predictable_Scroll = ExcelData.get("Predictable_Scroll");
	public static String Download_approvedPdf = ExcelData.get("Download_approvedPdf");
	public static String Functional_privilege_Header = ExcelData.get("Functional_privilege_Header");
	public static String seach_Filed = ExcelData.get("seach_Filed");
	public static String GlobalInput = ExcelData.get("GlobalInput");
	public static String search_option = ExcelData.get("search_option");
	public static String GlobalSEarchValu = ExcelData.get("GlobalSEarchValu");
	public static String ExpenseReport = ExcelData.get("ExpenseReport");
	public static String ExpenseReportTable = ExcelData.get("ExpenseReportTable");
	public static String InvoiceNumber = ExcelData.get("InvoiceNumber");
	public static String RefarenceNumber = ExcelData.get("RefarenceNumber");
	public static String Column = ExcelData.get("Column");
	public static String CheckBox_deselect = ExcelData.get("CheckBox_deselect");
	public static String input_Filed = ExcelData.get("input_Filed");
	public static String InvoiceNum = ExcelData.get("InvoiceNum");
	public static String referanceNum = ExcelData.get("referanceNum");
	public static String ExpenseReportClose = ExcelData.get("ExpenseReportClose");
	public static String Ventor_Global_Search = ExcelData.get("Ventor_Global_Search");
	public static String Ventor_Global_Seach_First_Field = ExcelData.get("Ventor_Global_Seach_First_Field");
	public static String columns_Button = ExcelData.get("columns_Button");
	public static String column_All_Select_Checkbox = ExcelData.get("column_All_Select_Checkbox");
	public static String column_Searchbox = ExcelData.get("column_Searchbox");
	public static String column_Checkbox = ExcelData.get("column_Checkbox");
	public static String column_Checkboxs = ExcelData.get("column_Checkboxs");
	public static String Vendor_Inv_Numbers = ExcelData.get("Vendor_Inv_Numbers");
	public static String Search_button = ExcelData.get("Search_button");
	public static String Mode_Field = ExcelData.get("Mode_Field");
	public static String Global_Input_Filed = ExcelData.get("Global_Input_Filed");
	public static String Horizontal_ = ExcelData.get("Horizontal_");
	public static String Global_Search_close = ExcelData.get("Global_Search_close");
	public static String ventor_Close = ExcelData.get("ventor_Close");
	public static String Horizonval_val = ExcelData.get("Horizonval_val");
	public static String Invoiced_Quantity = ExcelData.get("Invoiced_Quantity");
	public static String Total_cost_usd = ExcelData.get("Total_cost_usd");
	public static String ExpenseReportBackroundColor = ExcelData.get("ExpenseReportBackroundColor");
	public static String Vendor_Inv_Reg_Number = ExcelData.get("Vendor_Inv_Reg_Number");
	public static String Vendor_Invoic_Reg_scroll = ExcelData.get("Vendor_Invoic_Reg_scroll");
	public static String Vendor_Invoiced_qty = ExcelData.get("Vendor_Invoiced_qty");
	public static String Vendor_invoice_Amount = ExcelData.get("Vendor_invoice_Amount");
	public static String backroundcolor = ExcelData.get("backroundcolor");
	public static String Filtered_Row = ExcelData.get("Filtered_Row");
	public static String Select_Filter_Row = ExcelData.get("Select_Filter_Row");
	public static String Quantity_Column = ExcelData.get("Quantity_Column");
	public static String Vendor_Column = ExcelData.get("Vendor_Column");
	public static String Vendor_column_All_Select_Checkbox = ExcelData.get("Vendor_column_All_Select_Checkbox");
	public static String Vendar_Colunm_Input_Fiel = ExcelData.get("Vendar_Colunm_Input_Fiel");
	public static String ActivityRef_Number_Menu = ExcelData.get("ActivityRef_Number_Menu");
	public static String Filter_Option = ExcelData.get("Filter_Option");
	public static String Filter_Input2 = ExcelData.get("Filter_Input2");
	public static String Total_records = ExcelData.get("Total_records");
	public static String Invoice_Amount = ExcelData.get("Invoice_Amount");
	public static String ReferenceNumber = ExcelData.get("ReferenceNumber");
	public static String Condition_field = ExcelData.get("Condition_field");
	public static String First_row = ExcelData.get("First_row");
	public static String car_Number_val = ExcelData.get("car_Number_val");
	public static String expensereportpage = ExcelData.get("expensereportpage");
	public static String Open_Expenses = ExcelData.get("Open_Expenses");
	public static String Open_Expenses_Column = ExcelData.get("Open_Expenses_Column");
	public static String Open_Expense_Rows = ExcelData.get("Open_Expense_Rows");
	public static String Open_Expense_Rows_New = ExcelData.get("Open_Expense_Rows_New");
	public static String ChargeQuantity = ExcelData.get("ChargeQuantity");
	public static String OpsQuantity = ExcelData.get("OpsQuantity");
	public static String PredictCheckbox = ExcelData.get("PredictCheckbox");
	public static String Open_ExpensesSelectAll = ExcelData.get("Open_ExpensesSelectAll");
	public static String Open_Expense_Approve = ExcelData.get("Open_Expense_Approve");
	public static String popup_Message = ExcelData.get("popup_Message");
	public static String popup_Message_Yes_Button = ExcelData.get("popup_Message_Yes_Button");
	public static String popup_Message_No_Button = ExcelData.get("popup_Message_No_Button");
	public static String popup_Message_Ok_Button = ExcelData.get("popup_Message_Ok_Button");
	public static String Open_Expense_Submit = ExcelData.get("Open_Expense_Submit");
	public static String Open_Expense_Status = ExcelData.get("Open_Expense_Status");
	public static String Approved_Expenses = ExcelData.get("Approved_Expenses");
	public static String Approved_Expenses_Select_All = ExcelData.get("Approved_Expenses_Select_All");
	public static String Approved_Expenses_Rejected = ExcelData.get("Approved_Expenses_Rejected");
	public static String Open_Expenses_Reject = ExcelData.get("Open_Expenses_Reject");
	public static String Car_Edit_Option = ExcelData.get("Car_Edit_Option");
	public static String Unpredictable_Reporting = ExcelData.get("Unpredictable_Reporting");
	public static String Unpredictable_Reporting_Column = ExcelData.get("Unpredictable_Reporting_Column");
	public static String Unpredictable_Reporting_selecAllOption = ExcelData.get("Unpredictable_Reporting_selecAllOption");
	public static String Unpredictable_Reporting_SearchField = ExcelData.get("Unpredictable_Reporting_SearchField");
	public static String Unpredictable_Reporting_Checkbox = ExcelData.get("Unpredictable_Reporting_Checkbox");
	public static String Unpredictable_Reporting_Total_Recoed = ExcelData.get("Unpredictable_Reporting_Total_Recoed");
	public static String Unpredictable_Reporting_Condition_Filter = ExcelData.get("Unpredictable_Reporting_Condition_Filter");
	public static String column_Values = ExcelData.get("column_Values");
	public static String Contract_No_Filter_Inputs = ExcelData.get("Contract_No_Filter_Inputs");
	public static String Activity_Code_Input = ExcelData.get("Activity_Code_Input");
	public static String Head_Filter_Input = ExcelData.get("Head_Filter_Input");
	public static String UnPredictable_scroll = ExcelData.get("UnPredictable_scroll");
	public static String Qty_Input_Val = ExcelData.get("Qty_Input_Val");
	public static String Qty_Input_Field = ExcelData.get("Qty_Input_Field");
	public static String Charge_Rate = ExcelData.get("Charge_Rate");
	public static String Total_cost_val = ExcelData.get("Total_cost_val");
	public static String Unpredictable_Save = ExcelData.get("Unpredictable_Save");
	public static String Show_Total_Summary = ExcelData.get("Show_Total_Summary");
	public static String Show_Total_Amount_Summary = ExcelData.get("Show_Total_Amount_Summary");
	public static String Show_Total_Summary_Column = ExcelData.get("Show_Total_Summary_Column");
	public static String Show_Total_Summary_selecAllOption = ExcelData.get("Show_Total_Summary_selecAllOption");
	public static String Currency_option = ExcelData.get("Currency_option");
	public static String Show_Total_Summary_Ok = ExcelData.get("Show_Total_Summary_Ok");
	public static String Show_Total_rows = ExcelData.get("Show_Total_rows");
	public static String Show_Total_row_value_Currency = ExcelData.get("Show_Total_row_value_Currency");
	public static String Show_Total_row_value_value = ExcelData.get("Show_Total_row_value_value");
	public static String Show_Total_Main_Activity = ExcelData.get("Show_Total_Main_Activity");
	public static String Show_Row_Value = ExcelData.get("Show_Row_Value");
	public static String mis_submit = ExcelData.get("mis_submit");
	public static String miss_Rejec = ExcelData.get("miss_Rejec");
	public static String Rejected_status = ExcelData.get("Rejected_status");
	public static String Reject_colum = ExcelData.get("Reject_colum");
	public static String Reject_SelectAll = ExcelData.get("Reject_SelectAll");
	public static String Reject_Search_Field = ExcelData.get("Reject_Search_Field");
	public static String Reject_Input_Field = ExcelData.get("Reject_Input_Field");
	public static String Reject_FirstOption = ExcelData.get("Reject_FirstOption");
	public static String Rejected_Submitted = ExcelData.get("Rejected_Submitted");
	public static String Reject_Manually_Approved = ExcelData.get("Reject_Manually_Approved");
	public static String Rejected_Draft = ExcelData.get("Rejected_Draft");
	public static String Summary_Table_Headers = ExcelData.get("Summary_Table_Headers");
	public static String Summary_Table_Row = ExcelData.get("Summary_Table_Row");
	public static String Port_Value = ExcelData.get("Port_Value");
	public static String Activity_Code = ExcelData.get("Activity_Code");
	public static String Filtered_Username_Column_UCA = ExcelData.get("Filtered_Username_Column_UCA");
	public static String ExpensiveType_Input = ExcelData.get("ExpensiveType_Input");
	public static String car_Open_Btn = ExcelData.get("car_Open_Btn");
	public static String car_close_Btn = ExcelData.get("car_close_Btn");
	public static String total_cost_summary_window_Car = ExcelData.get("total_cost_summary_window_Car");
	public static String expense_report_Car = ExcelData.get("expense_report_Car");
	public static String total_cost_summary_table_Car = ExcelData.get("total_cost_summary_table_Car");
	public static String summary_ok_btn = ExcelData.get("summary_ok_btn");
	public static String approved_expenses_option = ExcelData.get("approved_expenses_option");
	public static String contract_Type_Dropdown = ExcelData.get("contract_Type_Dropdown");
	public static String enable_Supplementary_CAR_Gridcell_CI = ExcelData.get("enable_Supplementary_CAR_Gridcell_CI");
	public static String cost_Inbox_Module = ExcelData.get("cost_Inbox_Module");
	public static String valid_To_Date_PTM = ExcelData.get("valid_To_Date_PTM");
	public static String retrieved_Value_Select = ExcelData.get("retrieved_Value_Select");
	public static String select_first = ExcelData.get("select_first");
	public static String globalSearch_Condition_Dropdown1 = ExcelData.get("globalSearch_Condition_Dropdown1");
	public static String globalSearch_InputTextfield1 = ExcelData.get("globalSearch_InputTextfield1");
	public static String globalSearch_Frame_SearchButton = ExcelData.get("globalSearch_Frame_SearchButton");
	public static String globalSearch_Frame_ScrollBar = ExcelData.get("globalSearch_Frame_ScrollBar");
	public static String validFrom_Fiter_AGGrid = ExcelData.get("validFrom_Fiter_AGGrid");
	public static String Open_Expense_Rows_val = ExcelData.get("Open_Expense_Rows_val");
	public static String context_panel_Vc = ExcelData.get("context_panel_Vc");
	public static String Select_Row_UCA = ExcelData.get("Select_Row_UCA");
	public static String Approval_Limit_Input_UCA = ExcelData.get("Approval_Limit_Input_UCA");
	public static String Expensive_Type_Input_UCA = ExcelData.get("Expensive_Type_Input_UCA");
	public static String Activity_Code_option = ExcelData.get("Activity_Code_option");
	public static String Open_Expense_Approve_submitted = ExcelData.get("Open_Expense_Approve_submitted");
	public static String Open_Expense_Approve_Rejected = ExcelData.get("Open_Expense_Approve_Rejected");
	public static String Open_Expense_Empty_Screen = ExcelData.get("Open_Expense_Empty_Screen");
	public static String Approved_option = ExcelData.get("Approved_option");
	public static String Car_Screen_Manually_Approved = ExcelData.get("Car_Screen_Manually_Approved");
	public static String Car_status_Row_Option = ExcelData.get("Car_status_Row_Option");
	public static String Open_Table = ExcelData.get("Open_Table");
	public static String Open_TAble_record = ExcelData.get("Open_TAble_record");
	public static String show_Row_values = ExcelData.get("show_Row_values");
	public static String Show_Currency_Value = ExcelData.get("Show_Currency_Value");
	public static String Show_Amount_Value = ExcelData.get("Show_Amount_Value");
	public static String CarSummary_Table = ExcelData.get("CarSummary_Table");
	public static String GES_Filter = ExcelData.get("GES_Filter");
	public static String OpenExpense_Count = ExcelData.get("OpenExpense_Count");
	public static String ApprovedExpense_Count = ExcelData.get("ApprovedExpense_Count");
	public static String Approved_Scroller = ExcelData.get("Approved_Scroller");
	public static String Condition_Filter_CAR_APP = ExcelData.get("Condition_Filter_CAR_APP");
	public static String Approved_Total_CAR_APP = ExcelData.get("Approved_Total_CAR_APP");
	public static String Approved_table_CAR_APP = ExcelData.get("Approved_table_CAR_APP");

	
	
	
//unused
//	public static String Totalexpense_Currencybody = "Total expense summary currency body>//tbody[contains(@id,'gridtotalsummary_data')]";
//	public static String Column_SelectMenu = "Column Select Menu>//div[not(contains(@id,'main')) and @role='tabpanel' and @aria-hidden='false']//button[@ref='eToggleButton']"; //here we need to use contains only, in order to use multiple tab
//	public static String SelectAll_Column_CheckBox = "Select All Column Checkbox>//div[not(contains(@id,'main')) and @role='tabpanel' and @aria-hidden='false']//input[@aria-label='Toggle Select All Columns']";//here we need to use contains only, in order to use multiple tab
//	public static String Column_Search_Input = "Column Search Input>//div[not(contains(@id,'main')) and @role='tabpanel' and @aria-hidden='false']//input[@aria-label='Filter Columns Input']"; //here we need to use contains only, in order to use multiple tab
//	public static String Select_Column_tableHead = "Select table Headers>//div[@ref='sideBar']//span[text()='%s']";
//	public static String Select_Column_Head = "Select table Headers>//div[not(contains(@id,'main')) and @role='tabpanel' and @aria-hidden='false']//div[@ref='sideBar']//span[text()='%s']";
//	public static String add_Button_CAR_Summary = "add_Button_CAR_Summary>//button[contains(@id,'CRR_btnSumAdd')]";
//	public static String Equals_Option = "Equals_Option>//div[contains(@id,'nfr_sch_mu_pnl_content')]//span[text()='Equals']|//div[contains(@id,'twocolsearch')]//span[text()='Equals']";
//	public static String select_Button = "select_Button>//div[@aria-hidden='false']//span[text()='Select']//ancestor::button[1]";
//	public static String Filter_Field = "Filter_Field>(//div[@aria-hidden='false' and @role='dialog']//input[contains(@aria-label,'Filter Input')])[1]";
//	public static String Filter_Field1 = "Filter_Field1>(//div[@aria-hidden='false' and @role='dialog']//input[contains(@aria-label,'Filter Input')])[2]";
//	public static String Filter_Field2 = "Filter_Field2>(//div[@aria-hidden='false' and @role='dialog']//input[contains(@aria-label,'Filter Input')])[3]";
//	public static String Filter_Button = "Filter_Button>(//div[@aria-hidden='false' and @role='dialog']//button[@ref='eButtonShowMainFilter']//span)[1]";
//	public static String Filter_Button1 = "Filter_Button1>(//div[@aria-hidden='false' and @role='dialog']//button[@ref='eButtonShowMainFilter']//span)[2]";
//	public static String Filter_Button2 = "Filter_Button2>(//div[@aria-hidden='false' and @role='dialog']//button[@ref='eButtonShowMainFilter']//span)[3]";
//	public static String contains_Click = "contains_Click>(//div[@aria-hidden='false' and @role='dialog']//div[@ref='eDisplayField'])[1]";
//	public static String column_values_Right = "Column Values Right>//div[@aria-hidden='false' and @role='dialog']//div[@col-id='C2' and @role='gridcell']";
//	public static String DropDown_Select = "DropDown_Select>//div[contains(@id,'panel') and contains(@style,'display: block;')]//li[text()='%s']";
//	public static String Popup_Message = "Popup_Message>(//div[@class='ui-growl-item']//following::p)";

	
	
	
}
