package locators;

import java.util.Map;

import commonMethods.Testcases;
import commonMethods.Utils;

public interface Delivery_Order_Locators{

	Map<String, String> ExcelData = Utils.getDataAsMap(Testcases.conection_vale, "Delivery_Order", "Reference_Name", Testcases.environmentName);

	public static String Print_DO_Check_Box = ExcelData.get("Print_DO_Check_Box");
	public static String Delivery_Order_Pending_For_Approval = ExcelData.get("Delivery_Order_Pending_For_Approval");
	public static String Select_Bl_Checkbox = ExcelData.get("Select_Bl_Checkbox");
	public static String Delivery_Order_Approved_Status = ExcelData.get("Delivery_Order_Approved_Status");
	public static String Customer_Master_Search = ExcelData.get("Customer_Master_Search");
	public static String Customer_Master_Status = ExcelData.get("Customer_Master_Status");
	public static String Import_Invoice_Dock_ChkBox = ExcelData.get("Import_Invoice_Dock_ChkBox");
	public static String Import_Invoice_Factory_ChkBox = ExcelData.get("Import_Invoice_Factory_ChkBox");
	public static String Print_Header = ExcelData.get("Print_Header");
	public static String Select_BL_For_Approve = ExcelData.get("Select_BL_For_Approve");
	public static String DO_Print_Approval_Tool_Panel = ExcelData.get("DO_Print_Approval_Tool_Panel");
	public static String DO_Print_Approval_Filter = ExcelData.get("DO_Print_Approval_Filter");
	public static String DO_Print_Approval_BL_Filter = ExcelData.get("DO_Print_Approval_BL_Filter");
	public static String DO_Table_Headers = ExcelData.get("DO_Table_Headers");
	public static String DO_Table_Rows = ExcelData.get("DO_Table_Rows");
	public static String popup_Message = ExcelData.get("popup_Message");
	public static String popup_Message_Yes_Button = ExcelData.get("popup_Message_Yes_Button");
	public static String popup_Message_No_Button = ExcelData.get("popup_Message_No_Button");
	public static String popup_Message_Ok_Button = ExcelData.get("popup_Message_Ok_Button");
	public static String DO_Status = ExcelData.get("DO_Status");
	public static String deliveryOrderNumber_Textfield = ExcelData.get("deliveryOrderNumber_Textfield");
	public static String DO_show = ExcelData.get("DO_show");
	public static String DO_pop = ExcelData.get("DO_pop");
	public static String DO_pop_close = ExcelData.get("DO_pop_close");
	public static String Delivery_Order_Yes_Button = ExcelData.get("Delivery_Order_Yes_Button");
	public static String Import_Invoice_Checkbox = ExcelData.get("Import_Invoice_Checkbox");
	public static String Import_receipt_Checkbox = ExcelData.get("Import_receipt_Checkbox");
	public static String HBL_Num = ExcelData.get("HBL_Num");
	public static String HBL_Num_click2 = ExcelData.get("HBL_Num_click2");
	public static String HBL_Num_click1 = ExcelData.get("HBL_Num_click1");
	public static String HBL_Num_click = ExcelData.get("HBL_Num_click");
	public static String IGM_no_record_close = ExcelData.get("IGM_no_record_close");
	public static String IGM_no_record = ExcelData.get("IGM_no_record");
	public static String IGM_file_no = ExcelData.get("IGM_file_no");
	public static String IGM_Save_pop = ExcelData.get("IGM_Save_pop");
	public static String close_Button_PDF_Viewer = ExcelData.get("close_Button_PDF_Viewer");
	public static String DO_Number_SearchButton = ExcelData.get("DO_Number_SearchButton");
	public static String DO_Reset_Remarks_Area = ExcelData.get("DO_Reset_Remarks_Area");
	public static String DO_Reset_Button = ExcelData.get("DO_Reset_Button");
	public static String releaseTerminal_Textfield = ExcelData.get("releaseTerminal_Textfield");
	public static String name_Of_Clearing_Agent_Textfield = ExcelData.get("name_Of_Clearing_Agent_Textfield");
	public static String emptyReturnDepot_Textfield = ExcelData.get("emptyReturnDepot_Textfield");
	public static String DO_Service_Textfield = ExcelData.get("DO_Service_Textfield");
	public static String DO_Vessel_Textfield = ExcelData.get("DO_Vessel_Textfield");
	public static String DO_Voyage_Textfield = ExcelData.get("DO_Voyage_Textfield");
	public static String DO_Bound_Textfield = ExcelData.get("DO_Bound_Textfield");
	public static String DO_Port_Textfield = ExcelData.get("DO_Port_Textfield");
	public static String DO_Terminal_Textfield = ExcelData.get("DO_Terminal_Textfield");
	public static String DO_Issue_Location_IMD = ExcelData.get("DO_Issue_Location_IMD");
	public static String DO_Issue_Location_DO = ExcelData.get("DO_Issue_Location_DO");
	public static String DO_Column_Header = ExcelData.get("DO_Column_Header");
	public static String DO_Column_Row = ExcelData.get("DO_Column_Row");
	public static String DO_Container_Checkbox_Click = ExcelData.get("DO_Container_Checkbox_Click");
	public static String DO_Num_Tf = ExcelData.get("DO_Num_Tf");
	public static String Remarks_Tab_Column_Header = ExcelData.get("Remarks_Tab_Column_Header");
	public static String Remarks_Tab_Column_Row = ExcelData.get("Remarks_Tab_Column_Row");
	public static String POD_Value = ExcelData.get("POD_Value");
	public static String DO_Issue_Value = ExcelData.get("DO_Issue_Value");
	public static String DO_Button = ExcelData.get("DO_Button");
	public static String Import_Documentation_Container_Grid = ExcelData.get("Import_Documentation_Container_Grid");
	public static String DO_Container_Grid = ExcelData.get("DO_Container_Grid");
	public static String invoice_click = ExcelData.get("invoice_click");
	public static String Manifest_check = ExcelData.get("Manifest_check");
	public static String invoice_serach = ExcelData.get("invoice_serach");
	public static String INVOICE_issued = ExcelData.get("INVOICE_issued");
	public static String releaseTerminal_SearchButton = ExcelData.get("releaseTerminal_SearchButton");
	public static String terminalName_Filter = ExcelData.get("terminalName_Filter");
	public static String select_First_Row = ExcelData.get("select_First_Row");
	public static String deliveryOrder_Popup = ExcelData.get("deliveryOrder_Popup");
	public static String deliveryOrder_Popup_Yes = ExcelData.get("deliveryOrder_Popup_Yes");
	public static String nameOfClearingAgent_SearchButton = ExcelData.get("nameOfClearingAgent_SearchButton");
	public static String agentName_Filter = ExcelData.get("agentName_Filter");
	public static String emptyReturnDepot_SearchButton = ExcelData.get("emptyReturnDepot_SearchButton");
	public static String depotName_Filter = ExcelData.get("depotName_Filter");
	public static String iFrame = ExcelData.get("iFrame");
	public static String DO_Number_PDF = ExcelData.get("DO_Number_PDF");
	public static String receipt_Status_Filter = ExcelData.get("receipt_Status_Filter");
	public static String DO_Customer_Code_Search_Button = ExcelData.get("DO_Customer_Code_Search_Button");
	public static String select_All_Checkbox_DO = ExcelData.get("select_All_Checkbox_DO");
	public static String Deliver_Order_No_TF = ExcelData.get("Deliver_Order_No_TF");
	public static String DO_Status_Value = ExcelData.get("DO_Status_Value");
	public static String DO_BL_Input_TF = ExcelData.get("DO_BL_Input_TF");
	public static String cheque_Realisation = ExcelData.get("cheque_Realisation");
	public static String CR_CheckBox = ExcelData.get("CR_CheckBox");
	public static String Invoice_Reversal = ExcelData.get("Invoice_Reversal");
	public static String import_Invoice_Checkbox = ExcelData.get("import_Invoice_Checkbox");
	public static String customer_Code_Searchicon_DO = ExcelData.get("customer_Code_Searchicon_DO");
	public static String bl_Number_Filter = ExcelData.get("bl_Number_Filter");
	public static String click_Checkbox_By_Bl_Input = ExcelData.get("click_Checkbox_By_Bl_Input");
	public static String select_Button = ExcelData.get("select_Button");
	public static String status_Filter_DO = ExcelData.get("status_Filter_DO");
	public static String do_Number_Txtfield = ExcelData.get("do_Number_Txtfield");
	public static String jasper_Document = ExcelData.get("jasper_Document");
	public static String print_Document_Number_Check = ExcelData.get("print_Document_Number_Check");
	public static String delivery_Order_Module = ExcelData.get("delivery_Order_Module");
	public static String SearchBtn = ExcelData.get("SearchBtn");
	public static String bl_Num_Check_Imp_Doc = ExcelData.get("bl_Num_Check_Imp_Doc");
	public static String deliveryOrder_Popup_Message = ExcelData.get("deliveryOrder_Popup_Message");
	public static String DO_Popup_Close_Button = ExcelData.get("DO_Popup_Close_Button");
	public static String empty_Return_Depot_Field = ExcelData.get("empty_Return_Depot_Field");
	public static String guarantor_Search_Icon = ExcelData.get("guarantor_Search_Icon");
	public static String Cheque_Realizaation_Ok_Button = ExcelData.get("Cheque_Realizaation_Ok_Button");
	public static String receipt_Invoice_Details_Table_Do = ExcelData.get("receipt_Invoice_Details_Table_Do");
	public static String do_Status = ExcelData.get("do_Status");
	public static String x_option = ExcelData.get("x_option");
	public static String do_Table_Rows = ExcelData.get("do_Table_Rows");
	public static String do_Row_First_Chekbox = ExcelData.get("do_Row_First_Chekbox");
	public static String empty_Return_Form_Data = ExcelData.get("empty_Return_Form_Data");
	public static String do_Table_Headers = ExcelData.get("do_Table_Headers");
	public static String do_rows = ExcelData.get("do_rows");
	public static String do_Num_Txtfld = ExcelData.get("do_Num_Txtfld");
	public static String IGM_service_code = ExcelData.get("IGM_service_code");
	public static String IGM_vessel_code = ExcelData.get("IGM_vessel_code");
	public static String IGM_vessel_name = ExcelData.get("IGM_vessel_name");
	public static String IGM_voyage = ExcelData.get("IGM_voyage");
	public static String IGM_bound = ExcelData.get("IGM_bound");
	public static String IGM_port_code = ExcelData.get("IGM_port_code");
	public static String IGM_Terminal_code = ExcelData.get("IGM_Terminal_code");
	public static String IGM_Terminal_name = ExcelData.get("IGM_Terminal_name");
	public static String IGM_bl_select_box = ExcelData.get("IGM_bl_select_box");
	public static String remarks_Txtfld = ExcelData.get("remarks_Txtfld");
	public static String totalPages_PDF = ExcelData.get("totalPages_PDF");
	public static String Local_Manifiest_IGM = ExcelData.get("Local_Manifiest_IGM");
	public static String Transhipment_Manifiest_IGM = ExcelData.get("Transhipment_Manifiest_IGM");
	public static String Service_Btn_IGM = ExcelData.get("Service_Btn_IGM");
	public static String Vessel_Btn_IGM = ExcelData.get("Vessel_Btn_IGM");
	public static String Voyage_Btn_IGM = ExcelData.get("Voyage_Btn_IGM");
	public static String PortCode_Btn_IGM = ExcelData.get("PortCode_Btn_IGM");
	public static String Terminal_Btn_IGM = ExcelData.get("Terminal_Btn_IGM");
	public static String Show_Button_IGM = ExcelData.get("Show_Button_IGM");
	public static String IGM_Filter_Input = ExcelData.get("IGM_Filter_Input");
	public static String BL_Filter_input_IGM_grid = ExcelData.get("BL_Filter_input_IGM_grid");
	public static String Select_BL_NumCheck_IGM = ExcelData.get("Select_BL_NumCheck_IGM");
	public static String IGM_Ref_Input = ExcelData.get("IGM_Ref_Input");
	public static String Add_button_DeliveryOrder = ExcelData.get("Add_button_DeliveryOrder");
	public static String Show_Button_DeliverOrder = ExcelData.get("Show_Button_DeliverOrder");
	public static String Select_All_CheckBox_DeliveryOrder = ExcelData.get("Select_All_CheckBox_DeliveryOrder");
	public static String Deliver_Order_Date = ExcelData.get("Deliver_Order_Date");
	public static String DeliveryFilter_Input = ExcelData.get("DeliveryFilter_Input");
	public static String CFS_SELECT = ExcelData.get("CFS_SELECT");
	public static String cfs_Column = ExcelData.get("cfs_Column");
	public static String cfs_Column1 = ExcelData.get("cfs_Column1");
	public static String First_Row_Text_Check = ExcelData.get("First_Row_Text_Check");
	public static String second_Row_Text_Check = ExcelData.get("second_Row_Text_Check");
	public static String emptyReturnForm_PDF = ExcelData.get("emptyReturnForm_PDF");
	public static String pdf_PageNext_Button = ExcelData.get("pdf_PageNext_Button");
	public static String deliveryCustomer_Checkbox = ExcelData.get("deliveryCustomer_Checkbox");
	public static String deliveryCustomerCode_SearchButton = ExcelData.get("deliveryCustomerCode_SearchButton");
	public static String DO_CustomerCode_Textfield = ExcelData.get("DO_CustomerCode_Textfield");
	public static String DO_Name_Textfield = ExcelData.get("DO_Name_Textfield");
	public static String DO_Address_1_Textfield = ExcelData.get("DO_Address_1_Textfield");
	public static String DO_Address_2_Textfield = ExcelData.get("DO_Address_2_Textfield");
	public static String issuedInvoice_Row = ExcelData.get("issuedInvoice_Row");
	public static String IGM_bl_input = ExcelData.get("IGM_bl_input");
	public static String DO_Add_Button = ExcelData.get("DO_Add_Button");
	public static String emptyReturnForm_Checkbox = ExcelData.get("emptyReturnForm_Checkbox");
	public static String do_Table_Scroll = ExcelData.get("do_Table_Scroll");
	public static String DO_horizontal_Scroll = ExcelData.get("DO_horizontal_Scroll");
	public static String DO_Remarks_Field = ExcelData.get("DO_Remarks_Field");
	public static String DO_Approval_From_Date = ExcelData.get("DO_Approval_From_Date");
	public static String DO_Approval_To_Date = ExcelData.get("DO_Approval_To_Date");
	public static String DO_Approval_Show_Button = ExcelData.get("DO_Approval_Show_Button");
	public static String DO_Approval_Approve_Button = ExcelData.get("DO_Approval_Approve_Button");
	public static String DO_Approval_Revert_Button = ExcelData.get("DO_Approval_Revert_Button");
	public static String DO_Show_Button = ExcelData.get("DO_Show_Button");
	public static String SenderID_Search_Button_IGM = ExcelData.get("SenderID_Search_Button_IGM");
	public static String ReceiverID_Search_Button_IGM = ExcelData.get("ReceiverID_Search_Button_IGM");
	public static String BasicMsg_Search_Button_IGM = ExcelData.get("BasicMsg_Search_Button_IGM");
	public static String FillingMsg_Search_Button_IGM = ExcelData.get("FillingMsg_Search_Button_IGM");
	
	//Unused
	//public static String DO_Delete_Button = "DO_Delete_Button>//button[contains(@id,'DOP') and contains(@name,'btnTblDelete')]";
	//	public static String import_Invoice_Edit_Button="import_Invoice_Edit_Button>//div[@id='IIV-IIV_pnlMain_content']//button[contains(@id,'btnTblEdit')]";
	//	public static String import_Invoice_Issued_Button="import_Invoice_Issued_Button>(//input[@value='Issued']//following::span)[1]";
	//public static String IGM_search = "IGM_search>//button[contains(@id,'btnTblJdlgSearch')]";
	//public static String DO_Save_Button = "DO_Save_Button>//button[contains(@id,'DOP') and contains(@name,'btnsave')]";
	//public static String DO_Popup = "DO_Popup>//div[@id='lrp_cust_growl_container']//p";
	//	public static String DO_New_Button = "DO_New_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnTblNew')]";
	//	public static String DO_Search_Button = "DO_Search_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnTblJdlgSearch')]";
	//	public static String DO_Print_Button = "DO_Print_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnTblPrint')]";
	//public static String DO_Edit_Button = "DO_Edit_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnTblEdit')]";
	//public static String DO_Search_Btn="DO_Search_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnTblJdlgSearch')]";
	//public static String Cargo_Type="Cargo_Type>//label[text()='Cargo Type']//following::label[@id='IMH-IMH_CargoType']";
	//	public static String IGM_Save_Button = "IGM_Save_Button>//button[contains(@id,'IGM') and contains(@name,'btnsave')]";
	//	public static String receipt_new_button = "receipt_new_button>//button[contains(@id,'RCE') and contains(@id,'btnTblNew')]";
	//	public static String receipt_button="receipt_button>//button[@id='IIV-IIV_btnReceipt']";
	//	public static String Invoice_New_Button = "Invoice_New_Button>//div[@id='CRI-CRI_pnlMain_content']//button[contains(@id,'btnTblNew')]";
	//public static String Receipt_save2_Button="Receipt_Button>(//div[@role='toolbar']//button[contains(@id,'btnsave')])[2]";
	//public static String INVOICE_Save_Button = "INVOICE_Save_Button>//button[contains(@id,'CRI') and contains(@name,'btnsave')]";
	//	public static String INVOICE_pop = "INVOICE_pop>//h2[text()='Invoice']//following::span[2]";
	//	public static String INVOICE_pop_ok = "INVOICE_pop_ok>//h2[text()='Invoice']//following::button";
	//	public static String INVOICE_Edit = "INVOICE_Edit>//button[contains(@id,'CRI') and contains(@name,'btnTblEdit')]";
	//	public static String printDO_Checkbox = "printDO_Checkbox>//div[contains(@id,'DOP-DOP_printgrid')]//td[text()='Print DO']//..//span/parent::div";
	//	public static String pdfViewer = "pdfViewer>//span[@id='JSP_dialog_title']";
	//	public static String deliveryOrderReset_Popup = "deliveryOrderReset_Popup>(//h2[text()='Delivery Order Reset']//following::span)[2]";
	//	public static String deliveryOrderReset_Popup_Ok = "deliveryOrderReset_Popup_Ok>(//h2[text()='Delivery Order Reset']//following::span)[2]//following::button[text()='Ok']";
	//public static String chequeRealization_GlobalSearch="chequeRealization_GlobalSearch>//button[contains(@id,'CHA') and contains(@name,'btnTblJdlgSearch')]";
	//	public static String chequeRealization_Delete_Button="chequeRealization_Delete_Button>//button[contains(@id,'CHA') and contains(@name,'btnTblDelete')]";
	//	public static String globalSearch_CloseButton="globalSearch_CloseButton>//span[@id='nfr_sch_jdlg_title']/following-sibling::a[@aria-label='Close']";
	//public static String save_Button_DO="save_Button_DO>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnsave')]";
	//    public static String Delivery_Order_Popup="Delivery_Order_Popup>(//h2[text()='Delivery Order']//following::span)[2]";
	//public static String cheque_Search_Button="cheque_Search_Button>//div[contains(@id,'tblComponent')]//following::button[contains(@id,'btnTblJdlgSearch')]";
	//    public static String CR_Delete_Button="CR_Delete_Button>//div[contains(@id,'tblComponent')]//following::button[contains(@id,'btnTblDelete')]";
	//    public static String Receipt_SearcBtn="Receipt_SearcBtn>//div[contains(@id,'tblComponent')]//following::button[contains(@id,'btnTblJdlgSearch')]";
	//	public static String Import_Invoice_BL_Details_Table_Header="Import_Invoice_BL_Details_Table_Header>//thead[@id='IIV-IIV_gridBLDetails_head']//th";
	//	public static String Import_Invoice_BL_Details_Table_Row="Import_Invoice_BL_Details_Table_Row>//tbody[@id='IIV-IIV_gridBLDetails_data']//tr";
	//	public static String Testing_Option="Testing_Option>//div[contains(@id,'DOP_DOtable') and contains(@style,'display: block')]//li[@data-label='%s']";
	//		public static String import_Check="import_Check>//tbody[@id='DOP-DOP_DOtable_data']//tr[1]//div[@class='ui-cell-editor-output' and .='IMPORTS']";
	//		public static String testing_Check="testing_Check>//tbody[@id='DOP-DOP_DOtable_data']//tr[2]//div[@class='ui-cell-editor-output' and .='Testing']";
	//	public static String Search_Button_CD="Search_Button_CD>//div[@id='CAH-CAH_pnlMaingrid']//button[contains(@id,'btnTblJdlgSearch')]";
	//	public static String Delete_Button_CD="Delete_Button_CD>//div[@id='CAH-CAH_pnlMaingrid']//button[contains(@id,'btnTblDelete')]";
	//	public static String Doc_Agency ="Doc_Agency>//input[@id='FCN-FCN_txtDocAgencyCity']";
	//	public static String Profile_Dropdown ="Location_Dropdown>//label[@id='SWP-SWP_cmbSwitchType_label']";
	//	public static String Corporate_Profile ="Corporate_Location>//ul[@id='SWP-SWP_cmbSwitchType_items']//li[@data-label='Corporate']";
	//	public static String Location_Profile ="Location_Profile>//ul[@id='SWP-SWP_cmbSwitchType_items']//li[@data-label='Location']";
	//	public static String reset_Profile_Button="reset_Profile_Button>//button[@id='SWP-SWP_btnResetProfile']";
	//	public static String Module_Select = "Module_Select>//*[@id='nfr_topbar_autocomp_panel']//li[translate(@data-item-label, 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')=translate('%s', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz')]";
	//	public static String delete_Btn_Igm = "delete_Btn_Igm>//div[@id='IGM-IGM_pnlMain']//button[contains(@id,'btnTblDelete')]";
	//    public static String IGM_show = "IGM_show>//button[@id='IGM-IGM_show']";
	//	     public static String IGM_yes_button = "IGM_yes_button>//h2[text()='IGM EDI Generation']//following::button[2]";
	//	public static String bl_Num_Check_Imp_Doc="bl_Num_Check_Imp_Doc>//tbody[@id='IMH-IMH_remGrid_data']//tr/td[.='%s']//following-sibling::td";
	//		public static String delivery_Order_Popup = "deliveryOrder_Popup>(//div[@id='lrp_cust_growl_container']//following::span[text()='Delivery Order'])[1]//following::p";
	//		public static String DO_save_Button = "DO_save_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnsave')]";
	//		public static String customer_Details_Panel = "customer_Details_Panel>//div[@id='nfr-multi-div']//div[@ref='eCenterViewport']";
	//		public static String table_path="table_path>//div[@id='IMH-IMH_gridCharge1']";
	//		 public static String IGM_New_Button = "IGM_New_Button>//div[@id='IGM-IGM_pnlMain']//button[contains(@id,'btnTblNew')]";
	//	public static String   global_Field1="global_Field1>//select[@id='type']";
	//	public static String receipt_Tab="receipt_Tab>//ul[@id='nfr_tabmdl_header']/li[@moduleid='RCE']//i[@class='fa fa-remove mdlclose']";
	//	public static String cheque_Real_Tab="cheque_Real_Tab>//ul[@id='nfr_tabmdl_header']/li[@moduleid='CHA']//i[@class='fa fa-remove mdlclose']";
	//	public static String receipt_New_Button="receipt_New_Button>//div[@role='toolbar']//button[contains(@id,'btnTblNew')]";
	//	public static String receipt_Advance_Button="receipt_Advance_Button>//input[@id='RCE-RCE_rdbgrpReceiptMode-1']//following::span[text()='Advance']";
	//	public static String receipt_Customer_Name="receipt_Customer_Name>//input[@id='RCE-RCE_txtCustName']";
	//	public static String receipt_Address_Field="receipt_Address_Field>//textarea[@id='RCE-RCE_txtAddress']";
	//	public static String receipt_Payer_Code="receipt_Payer_Code>//input[@id='RCE-RCE_txtpayercode']";
	//	public static String receipt_Payer_Name="receipt_Payer_Name>//input[@id='RCE-RCE_txtpayer']";
	//	public static String receipt_Payment_Details_Tab="receipt_Payment_Details_Tab>//div[@id='RCE-RCE_TabbedPane1']//ul[@role='tablist']//a[text()='Payment Details']//ancestor::li";
	//	public static String receipt_Mode_dropdown="receipt_Mode_dropdown>//label[@id='RCE-RCE_cmbmodeofpay_label']";
	//	public static String receipt_Mode_Select="receipt_Mode_Select>//li[text()='%s']";
	//	public static String receipt_Number_TF="receipt_Number_TF>//input[@id='RCE-RCE_txtChqNum']";
	//	public static String receipt_Payable_At_Dropdown="receipt_Payable_At_Dropdown>//div[@id='RCE-RCE_cmbPayableAt']";
	//	public static String receipt_Payable_At_Select="receipt_Payable_At_Select>//li[text()='%s']";
	//	public static String receipt_Currency_Search_Button="receipt_Currency_Search_Button>//button[@id='RCE-RCE_btnCur-RCE_btnCur']";
	//	public static String receipt_Currency_Input_Tf="receipt_Currency_Input_Tf>//input[@aria-label='CurrencyCode Filter Input']";
	//	public static String receipt_Bank_Search_Button="receipt_Bank_Search_Button>//button[@id='RCE-RCE_btnBank-RCE_btnBank']";
	//	public static String receipt_Bank_Name_TF="receipt_Bank_Name_TF>//input[@aria-label='BankName Filter Input']";
	//	public static String value_Select="value_Select>//div[@id='nfr-twocolsearch-div']//div[@ref='eCenterContainer']//div[@row-index='0']";
	//	public static String receipt_Amount_TF="receipt_Amount_TF>//input[@id='RCE-RCE_txtChPayAmt_input']";
	//	public static String receipt_Roe_TF="receipt_Roe_TF>//input[@id='RCE-RCE_txtChqRoe']";
	//	public static String receipt_Amount_Fetched_TF="receipt_Amount_Fetched_TF>//input[@id='RCE-RCE_txtChPayHomeAmt']";
	//	public static String receipt_Add_Button="receipt_Add_Button>//button[@id='RCE-RCE_btnPayAdd']";
	//	public static String receipt_Save_Button="receipt_Save_Button>//div[@role='toolbar']//button[contains(@id,'btnsave')]";
	//	public static String receipt_Popup_Ok_Button="receipt_Popup_Ok_Button>//h2[text()='Receipt']//following::button";
	//	public static String receipt_Num_field="receipt_Num_field>//input[@id='RCE-RCE_txtReceiptNo']";
	//	public static String receipt_Delete_Button="receipt_Delete_Button>//div[@role='toolbar']//button[contains(@id,'btnTblDelete')]";
	//	public static String receipt_Remarks_Field="receipt_Remarks_Field>//textarea[@id='RCE-RCE_txtaraMasRemark']";
	//	public static String receipt_Popup_Yes_Button="receipt_Popup_Yes_Button>(//h2[text()='Receipt']//following::button)[2]";
	//	public static String Select_Value="Select_Value>//div[@id='nfr_sch_multicolumn']//div[@ref='eCenterContainer']//div[@row-index='0']";
	//	public static String DO_Guarantor_Search_Button="DO_Guarantor_Search_Button>//button[@id='DOP-DOP_btnguarantor-DOP_btnguarantor']";
	//	 public static String releaseTerminal_Textfield="releaseTerminal_Textfield>//input[@id='DOP-DOP_txtrlsterminal']";
	//	    public static String name_Of_Clearing_Agent_Textfield="name_Of_Clearing_Agent_Textfield>//input[@id='DOP-DOP_txtclragntname']";
	//	    public static String emptyReturnDepot_Textfield="emptyReturnDepot_Textfield>//input[@id='DOP-DOP_txtEmptyRtnDepot']";
	//	    public static String prepaidCgarges_Tab_Scroll_IMD="prepaidCgarges_Tab_Scroll_IMD>//div[@id='IMH-IMH_prepaidCharges']//div[@class='ui-datatable-scrollable-body']";
	//	    public static String deliveryOrder_Popup_Message="deliveryOrder_Popup_Message>//label[@id='LoadPlan_form-lblLoadPlan']";
	//		public static String DO_Popup_Close_Button = "DO_Popup_Close_Button>//div[@id='setLoadPlannedBls_id']//a[@aria-label='Close']";
	//	    public static String invoiceMode_Dropdown="invoiceMode_Dropdown>//div[@id='CRI-CRI_cmbinvoicemode']";
	//	    public static String invoiceMode="invoiceMode>//ul[@id='CRI-CRI_cmbinvoicemode_items']/li[text()='%s']";
	//	    public static String DO_Service_Textfield = "DO_Service_Textfield>//input[@id='DOP-DOP_txtsercode']";
	//		public static String DO_Vessel_Textfield = "DO_Vessel_Textfield>//input[@id='DOP-DOP_txtvslcode']";
	//		public static String DO_Voyage_Textfield = "DO_Voyage_Textfield>//input[@id='DOP-DOP_txtvoyage']";
	//		public static String DO_Bound_Textfield = "DO_Bound_Textfield>//input[@id='DOP-DOP_txtbound']";
	//		public static String DO_Port_Textfield = "DO_Port_Textfield>//input[@id='DOP-DOP_txtoprprtcde']";
	//		public static String DO_Terminal_Textfield = "DO_Terminal_Textfield>//input[@id='DOP-DOP_txtterminal']";
	//		public static String DO_Issue_Location_IMD = "DO_Issue_Location_IMD>//input[@id='IMH-IMH_txtDoIssueLoc']";
	//		public static String DO_Issue_Location_DO = "DO_Issue_Location_DO>//input[@id='DOP-DOP_txtport']";
	//		public static String do_Table_Checkboxes="do_Table_Checkboxes>//tbody[@id='DOP-DOP_DOtable_data']//td[1][@role='gridcell']//input[@type='checkbox']";
	//public static String  delete_Msg="delete_Msg>//h2[.='Delivery Order']/..//span[2]";
	//	public static String do_deleted="do_deleted>//div[@id='lrp_cust_growl_container']//p[.='Delivery Order deleted.']";
	//	public static String  addtional_Save_Receipt="addtional_Save_Receipt>//button[contains(@id,'RCE') and contains(@name,'btnsave')]";
	//	public static String   receipt_Number_Textfield="receipt_Number_Textfield>//input[@id='RCE-RCE_txtReceiptNo']";
	//	public static String   additional_Search_Icon_Receipt="additional_Search_Icon_Receipt>//button[contains(@id,'RCE')  and contains(@name,'btnTblJdlgSearch')]";
	//public static String againstInvoice_Button = "againstInvoice_Button>//input[@value='AgainstInvoice']/parent::div";
	//	public static String selectedInvoice_Button = "selectedInvoice_Button>//input[@value='SelectedInvoice']/parent::div";
	//	public static String selectedInvoice_Add_Button = "selectedInvoice_Add_Button>//button[@id='RCE-RCE_btnOtAdd']";
	//	public static String selectedInvoice_Remove_Button = "selectedInvoice_Remove_Button>//button[@id='RCE-RCE_btnOtRemove']";
	//	public static String selectedInvoice_Show_Button = "selectedInvoice_Show_Button>//button[@id='RCE-RCE_btninvoicelist']";
	//	public static String type_Select3="type_Select3>//select[@id='third_type']";
	//	public static String invoiceNumber_InputField="invoiceNumber_InputField>//tbody[@id='RCE-RCE_jinvlist_data']//input";
	//	public static String mode_Select="mode_Select>//div[@id='RCE-RCE_cmbmodeofpay']";
	//	public static String wire_Transfer_Option="wire_Transfer_Option>//li[.='Wire Transfer']";
	//	public static String number_Txtfield="number_Txtfield>//input[@id='RCE-RCE_txtChqNum']";
	//	public static String bank_Search_Icon="bank_Search_Icon>//button[@id='RCE-RCE_btnBank-RCE_btnBank']";
	//	public static String bank_Name_Txtfield="bank_Name_Txtfield>//input[@aria-label='BankName Filter Input']";
	//	public static String save_btn_Receipt="save_btn_Receipt>//div[@role='toolbar']//button[3]";
	//	public static String auto_Realise_save_Popup="auto_Realise_save_Popup>//h2/..//span[2]";
	//	public static String payer_Txtfield="payer_Txtfield>//input[@id='RCE-RCE_txtpayercode']";
	//	public static String cust_Name_Txtfield="cust_Name_Txtfield>//input[@id='RCE-RCE_txtCustCode']";
	//	public static String payer_Name="payer_Name>//input[@id='RCE-RCE_txtpayer']";
	//	public static String payer_Address="payer_Address>//textarea[@id='RCE-RCE_txtpayeraddress']";
	//	public static String total_Outstanding_Balance="total_Outstanding_Balance>//input[@id='RCE-RCE_txtTotalBalance']";
	//	public static String invoice_Num_Cell="invoice_Num_Cell>//tbody[@id='RCE-RCE_invoicesummarygrid_data']//tr[1]//td[4]";
	//	public static String payment_Details_Tab="payment_Details_Tab>//div[@id='RCE-RCE_TabbedPane1']//a[.='Payment Details']";
	//	public static String receipt_Num_Txtfield="receipt_Num_Txtfield>//input[@id='RCE-RCE_txtReceiptNo']";
	//	public static String search_Icon_Cheque_Real="search_Icon_Cheque_Real>//div[@id='CHA-CHA_pnlMain_content']//button[contains(@id,'btnTblJdlgSearch')]";
	//    public static String  click_Checkbox_With_Receipt_Number="click_Checkbox_With_Receipt_Number>//div[@ref='eCenterContainer']//div[@col-id='recNo' and .='%s']/..//input[1]";
	//    public static String  delete_Btn_Cheque_Real="delete_Btn_Cheque_Real>//div[@id='CHA-CHA_pnlMain_content']//button[5]";
	//    public static String   reverse_Success_Popup="reverse_Success_Popup>//h2//following::span[2]";
	//    public static String  delete_Btn_Receipt_Module="delete_Btn_Receipt_Module>//div[@id='RCE-RCE_pgMain_content']//button[5]";
	//    public static String  receipt_Remarks_Textarea="receipt_Remarks_Textarea>//textarea[@id='RCE-RCE_txtaraMasRemark']";
	//public static String Import_Invoice_Bl_Num_TF="Import_Invoice_Bl_Num_TF>//input[@id='IIV-IIV_txtBLNo']";
	//  public static String DO_Condition_select="DO_Condition_select>//select[@id='second_type']";  
	//  public static String SearchBtn="SearchBtn>//button[@id='myBtn']";
	//  public static String HBl_TF="HBl_TF>//input[@aria-label='HBL Number Filter Input']";
	//	public static String reciept_Button = "reciept_Button>//button[@id='IIV-IIV_btnReceipt']";
	//public static String DO_Column_Header="DO_Column_Header>//thead[@id='DOP-DOP_DOtable_head']//th";
	// public static String DO_Column_Row="DO_Column_Row>//tbody[@id='DOP-DOP_DOtable_data']//tr";   
	// public static String DO_Container_Checkbox_Click="DO_Container_Checkbox_Click>//tr[@data-rk='%s']/td/input[@type='checkbox']";   
	// public static String DO_Num_Tf="DO_Num_Tf>//input[@id='DOP-DOP_txtdelnum']";
	// public static String Remarks_Tab_Column_Header="Remarks_Tab_Column_Header>//thead[@id='IMH-IMH_remGrid_head']//th";
	// public static String Remarks_Tab_Column_Row="Remarks_Tab_Column_Row>//tbody[@id='IMH-IMH_remGrid_data']//tr";
	// public static String DO_Search_Btn="DO_Search_Button>//div[@id='DOP-DOP_toolBar']//button[contains(@id,'btnTblJdlgSearch')]";
	// public static String POD_Value="POD_Value>//label[@id='IMH-IMH_txtPOD']";
	// public static String DO_Issue_Value="DO_Issue_Value>//input[@id='IMH-IMH_txtDoIssueLoc']";
	// public static String DO_Button="DO_Button>//button[@id='IMH-IMH_btnDeliveryOrderNavigate']";
	// //public static String type_Select2="type_Select2>//select[@id='second_type']";
	// public static String Import_Documentation_Container_Grid="Import_Documentation_Container_Grid>//tbody[@id='IMH-IMH_gridContainer_data']//tr";
	// public static String DO_Container_Grid="DO_Container_Grid>//tbody[@id='DOP-DOP_DOtable_data']//tr";
	// public static String type_Select1="type_Select1>//select[@onchange='myFunction1()']";
	//	public static String DO_Save_Popup = "DO_Popup>//div[@id='lrp_cust_growl_container']//p";
	//	public static String Date_select ="Date_select>//a[text()='%s']";
	//	public static String DO_Number_SearchButton = "DO_Number_SearchButton>//button[@id='DORform-DOR_btnDeliveryOrdNo']";
	//	public static String DO_Reset_Remarks_Area = "DO_Reset_Remarks_Area>//textarea[@id='DORform-DOR_txtRemarks']";
	//	public static String DO_Reset_Button = "DO_Reset_Button>//button[@id='DORform-DOR_btnDeliveryOrdReset']";
	//	public static String close_Button_PDF_Viewer = "close_Button_PDF_Viewer>//div[@id='JSP_dialog']//a[@aria-label='Close']";
	//	public static String delivery_Order_Module = "delivery_Order_Module>//li[@moduleid='DOP']";
	//	public static String retrieved_Value_select="retrieved_Value_select>//table[@id='nfr_sch_jdlg_form-nfr_sch_jd_pnl']//div[@ref='centerContainer']//div[@role='row']";
	//	public static String first_row="first_row>//div[@id='nfr-jdlgGrid-div']//div[@ref='eCenterContainer']//div[@row-index='0']";
	//	public static String panel_First_Row_Click="panel_First_Row_Click>//div[@ref='eCenterContainer']//div[@row-index='0']";
	//	public static String deposit_Bank_Search_Icon="deposit_Bank_Search_Icon>//button[@id='RCE-RCE_btndepBank']";
	//	public static String deposit_Bank_Txtfield="deposit_Bank_Txtfield>//input[@aria-label='Bank Name Filter Input']";
	//	public static String add_Payment_Details="add_Payment_Details>//button[@id='RCE-RCE_btnPayAdd']//span[.='Add']";
	//	public static String invoiceAndReceipt_Tab="invoiceAndReceipt_Tab>//div[@id='RCE-RCE_TabbedPane1']//li[2]";
	//	public static String allocate_Btn="allocate_Btn>//button[@id='RCE-RCE_btninvoice']";
	//public static String jsp_Doc="JSP_DocumentViewer";
	//	public static String import_Invoice_Checkbox_IMD="import_Invoice_Checkbox>//div[@id='IMH-IMH_chkImportInvoice']/div[contains(@class,'ui-state-disabled')]";
	//public static String horizontal_Scroll="horizontal_Scroll>//form[@id='nfr_sch_jdlg_form']//div[contains(@class,'horizontal') and contains(@ref,'eViewport')]";
	//	public static String print_Do_Checkbox="print_Do_Checkbox>//div[contains(@id,'DOP_printgrid')]//div[2][contains(@class,'chkbox')]";

}
