package locators;

import java.util.Map;

import commonMethods.Testcases;
import commonMethods.Utils;

public interface Ecommerce_Validator_Locators {

	
	Map<String, String> ExcelData = Utils.getDataAsMap(Testcases.conection_vale, "Ecommerce_Validator", "Reference_Name", Testcases.environmentName);

	public static String ECV_Ext_ref_No = ExcelData.get("ECV_Ext_ref_No");
	public static String ECV_Service = ExcelData.get("ECV_Service");
	public static String ECV_Equip_Quantity = ExcelData.get("ECV_Equip_Quantity");
	public static String ECV_Equipment_ID_DD = ExcelData.get("ECV_Equipment_ID_DD");
	public static String ECV_Cargo_Weight_Field = ExcelData.get("ECV_Cargo_Weight_Field");
	public static String ECV_Commodity_Group_Field = ExcelData.get("ECV_Commodity_Group_Field");
	public static String ECV_HS_Code_Search_Button = ExcelData.get("ECV_HS_Code_Search_Button");
	public static String ECV_Commodity_Description = ExcelData.get("ECV_Commodity_Description");
	public static String EBK_Accecpt_Button = ExcelData.get("EBK_Accecpt_Button");
	public static String EBK_Mismatch_Header_Message = ExcelData.get("EBK_Mismatch_Header_Message");
	public static String EBK_Mismatch_Header_Message_Yes_Button = ExcelData.get("EBK_Mismatch_Header_Message_Yes_Button");
	public static String EBK_Mismatch_Header_Message_No_Button = ExcelData.get("EBK_Mismatch_Header_Message_No_Button");
	public static String EBK_Mismatch_Header_Message_Cancel_Button = ExcelData.get("EBK_Mismatch_Header_Message_Cancel_Button");
	public static String EBK_Customer_Tab = ExcelData.get("EBK_Customer_Tab");
	public static String EBK_ENS_Declaration_Tab = ExcelData.get("EBK_ENS_Declaration_Tab");
	public static String EBK_Customer_Table_CustomerType = ExcelData.get("EBK_Customer_Table_CustomerType");
	public static String EBK_Customer_Remove_Button = ExcelData.get("EBK_Customer_Remove_Button");
	public static String EBK_Customer_Table_Rows = ExcelData.get("EBK_Customer_Table_Rows");
	public static String EBK_Customer_Table_Headers = ExcelData.get("EBK_Customer_Table_Headers");
	public static String EBK_Customer_Table_Horizontal_scrollbar = ExcelData.get("EBK_Customer_Table_Horizontal_scrollbar");
	public static String EBK_Customer_Table_Header_Names = ExcelData.get("EBK_Customer_Table_Header_Names");
	public static String EBK_Discharge_Port_Value = ExcelData.get("EBK_Discharge_Port_Value");
	public static String EBK_Single_Filling_Button = ExcelData.get("EBK_Single_Filling_Button");
	public static String EBK_Multiple_Filling_Button = ExcelData.get("EBK_Multiple_Filling_Button");
	public static String EBK_Straight_BL_Button = ExcelData.get("EBK_Straight_BL_Button");
	public static String EBK_Master_BL_Button = ExcelData.get("EBK_Master_BL_Button");
	public static String EBK_Of_Payment_Button = ExcelData.get("EBK_Of_Payment_Button");
	public static String EBK_Master_Tab_NA_Button = ExcelData.get("EBK_Master_Tab_NA_Button");
	public static String EBK_Master_Tab_Partial_Filling_Button = ExcelData.get("EBK_Master_Tab_Partial_Filling_Button");
	public static String EBK_Master_Tab_Single_Filling_Button = ExcelData.get("EBK_Master_Tab_Single_Filling_Button");
	public static String EBK_Master_Tab_NA_Value = ExcelData.get("EBK_Master_Tab_NA_Value");
	public static String EBK_Master_Tab_Partial_Filling_Value = ExcelData.get("EBK_Master_Tab_Partial_Filling_Value");
	public static String EBK_Master_Tab_Single_Filling_Value = ExcelData.get("EBK_Master_Tab_Single_Filling_Value");
	public static String multiple_Filing_Agreement_Checkbox = ExcelData.get("multiple_Filing_Agreement_Checkbox");
	public static String ENS_Filling_Type_Dropdown = ExcelData.get("ENS_Filling_Type_Dropdown");
	public static String EG_Retrieved_Record_AG_Gridcell = ExcelData.get("EG_Retrieved_Record_AG_Gridcell");
	public static String Discharge1 = ExcelData.get("Discharge1");
	public static String Discharge2 = ExcelData.get("Discharge2");
	public static String EV_Routing_Edit = ExcelData.get("EV_Routing_Edit");
	public static String Routing = ExcelData.get("Routing");
	public static String ok = ExcelData.get("ok");
	public static String Service = ExcelData.get("Service");
	public static String Route_data2 = ExcelData.get("Route_data2");
	public static String Header_Panel_EComm_Validator = ExcelData.get("Header_Panel_EComm_Validator");
	public static String Header_Panel_List_Ecomm_Validator = ExcelData.get("Header_Panel_List_Ecomm_Validator");
	public static String Routing_Select_Column_EComm_Validator = ExcelData.get("Routing_Select_Column_EComm_Validator");
	public static String Okay_Button_EComm_Validator = ExcelData.get("Okay_Button_EComm_Validator");
	public static String Service_Input_EComm_Validator = ExcelData.get("Service_Input_EComm_Validator");
	public static String Vessel_Search_Input_Ecomm_Validator = ExcelData.get("Vessel_Search_Input_Ecomm_Validator");
	public static String Voyage_Search_Input_Ecomm_Validator = ExcelData.get("Voyage_Search_Input_Ecomm_Validator");
	public static String Bound_Search_Input_Ecomm_Validator = ExcelData.get("Bound_Search_Input_Ecomm_Validator");
	public static String First_Row_EComm_Validator = ExcelData.get("First_Row_EComm_Validator");
	public static String Select_Button_EComm_Validator = ExcelData.get("Select_Button_EComm_Validator");
	public static String Accept_Btn_EComm_Validator = ExcelData.get("Accept_Btn_EComm_Validator");
	public static String Cancel_Button_Ecomm_Validator = ExcelData.get("Cancel_Button_Ecomm_Validator");
	public static String Invalid_Column_EComm_Validator = ExcelData.get("Invalid_Column_EComm_Validator");
	public static String Commodity_RowEdit_Ecomm_Validator = ExcelData.get("Commodity_RowEdit_Ecomm_Validator");
	public static String HS_Code_Search_Ecomm_Validator = ExcelData.get("HS_Code_Search_Ecomm_Validator");
	public static String HS_Code_Value_Ecomm_Validator = ExcelData.get("HS_Code_Value_Ecomm_Validator");
	public static String Commodity_Ok_Btn_Ecom_Validator = ExcelData.get("Commodity_Ok_Btn_Ecom_Validator");
	public static String Edit_btn_Commodity_EComm_Validator = ExcelData.get("Edit_btn_Commodity_EComm_Validator");
	public static String Submit_Btn_EComm_Validator = ExcelData.get("Submit_Btn_EComm_Validator");
	public static String Booking_Num_Field_EComm_Validator = ExcelData.get("Booking_Num_Field_EComm_Validator");
	public static String Update_Booking_Checbox_Ecomm_Validator = ExcelData.get("Update_Booking_Checbox_Ecomm_Validator");
	public static String BL_Number_Field_EComm_Validator = ExcelData.get("BL_Number_Field_EComm_Validator");
	public static String Book_Agency_Input_Ecomm_Validator = ExcelData.get("Book_Agency_Input_Ecomm_Validator");
	public static String Load_Input_EComm_Validator = ExcelData.get("Load_Input_EComm_Validator");
	public static String Customer_Table_EComm_Validator = ExcelData.get("Customer_Table_EComm_Validator");
	public static String SelectCustomer_EComm_Validator = ExcelData.get("SelectCustomer_EComm_Validator");
	public static String CustomerEdit_Row_EComm_Validator = ExcelData.get("CustomerEdit_Row_EComm_Validator");
	public static String Customer_Copy_EComm_Validator = ExcelData.get("Customer_Copy_EComm_Validator");
	public static String Paste_Options_EComm_Validator = ExcelData.get("Paste_Options_EComm_Validator");
	public static String Paste_Select_Columns_EComm_Validator = ExcelData.get("Paste_Select_Columns_EComm_Validator");
	public static String Paste_Btn_EComm_Validator = ExcelData.get("Paste_Btn_EComm_Validator");
	public static String Close_PasteOptions_EComm_Validator = ExcelData.get("Close_PasteOptions_EComm_Validator");
	public static String Customer_Table_Headers_EComm_Validator = ExcelData.get("Customer_Table_Headers_EComm_Validator");
	public static String Customer_Type_Column_EComm_Validator = ExcelData.get("Customer_Type_Column_EComm_Validator");
	public static String Commodity_Row_Value_EComm_Validator = ExcelData.get("Commodity_Row_Value_EComm_Validator");
	public static String Commodity_Row_Edit_Ecomm_Validator = ExcelData.get("Commodity_Row_Edit_Ecomm_Validator");
	public static String Cargo_Weight_Input_Commodity_Ecomm_Validator = ExcelData.get("Cargo_Weight_Input_Commodity_Ecomm_Validator");
	public static String Commodity_Table_EComm_Validator = ExcelData.get("Commodity_Table_EComm_Validator");
	public static String Commodity_Table_Headers_EComm_Validator = ExcelData.get("Commodity_Table_Headers_EComm_Validator");
	public static String Container_Table_Headers_EComm_Validator = ExcelData.get("Container_Table_Headers_EComm_Validator");
	public static String Container_Table_Rows_EComm_Validator = ExcelData.get("Container_Table_Rows_EComm_Validator");
	public static String Commodity_Table_Row_EComm_Validator = ExcelData.get("Commodity_Table_Row_EComm_Validator");
	public static String AP_Column_CustomerTable_EComm_Validator = ExcelData.get("AP_Column_CustomerTable_EComm_Validator");
	public static String Customer_Table_RowSelect_EComm_Validator = ExcelData.get("Customer_Table_RowSelect_EComm_Validator");
	public static String Customer_Table_Rows_EComm_Validator = ExcelData.get("Customer_Table_Rows_EComm_Validator");
	public static String Remove_Btn_Customer_EComm_Validator = ExcelData.get("Remove_Btn_Customer_EComm_Validator");
	public static String EV_Refno = ExcelData.get("EV_Refno");
	public static String Routing_Table_HeaderList_EV = ExcelData.get("Routing_Table_HeaderList_EV");
	public static String Routing_Table_Rows_EV = ExcelData.get("Routing_Table_Rows_EV");
	public static String Selected_Routing_Terminal_EV = ExcelData.get("Selected_Routing_Terminal_EV");
	public static String Selected_Routing_Row_EV = ExcelData.get("Selected_Routing_Row_EV");
	public static String Routing_Service_value_EV = ExcelData.get("Routing_Service_value_EV");
	public static String Select_Routing_Row_value_EV = ExcelData.get("Select_Routing_Row_value_EV");
	public static String Routing_terminal_EV = ExcelData.get("Routing_terminal_EV");
	public static String Schedule_terminal_EV = ExcelData.get("Schedule_terminal_EV");
	public static String Routing_Add_Btn_EComm_Validator = ExcelData.get("Routing_Add_Btn_EComm_Validator");
	public static String Routing_Select_Tab_EComm_Validator = ExcelData.get("Routing_Select_Tab_EComm_Validator");
	public static String Booking_Decline_Btn_Ecomm_Validator = ExcelData.get("Booking_Decline_Btn_Ecomm_Validator");
	public static String Decline_Remark_Input_EV = ExcelData.get("Decline_Remark_Input_EV");
	public static String Decline_Remark_Ok_Btn_EV = ExcelData.get("Decline_Remark_Ok_Btn_EV");
	public static String Ed = ExcelData.get("Ed");
	public static String Edit1 = ExcelData.get("Edit1");
	public static String SGSINPLD = ExcelData.get("SGSINPLD");
	public static String SGSINPOD = ExcelData.get("SGSINPOD");
	public static String POLDATA = ExcelData.get("POLDATA");
	public static String PLADATA = ExcelData.get("PLADATA");
	public static String BOUNDD = ExcelData.get("BOUNDD");
	public static String VOYAGE = ExcelData.get("VOYAGE");
	public static String VESSEL = ExcelData.get("VESSEL");
	public static String Processing_Locator = ExcelData.get("Processing_Locator");
	public static String customer_Agency_Mapping_Module_Title = ExcelData.get("customer_Agency_Mapping_Module_Title");
	public static String ETC_Module_Click = ExcelData.get("ETC_Module_Click");
	public static String Routing_Select_ECom_Validator = ExcelData.get("Routing_Select_ECom_Validator");
	public static String Master_Tab_NA_Button_EBK = ExcelData.get("Master_Tab_NA_Button_EBK");
	public static String Master_Tab_Partial_Filling_Button_EBK = ExcelData.get("Master_Tab_Partial_Filling_Button_EBK");
	public static String Master_Tab_Single_Filling_Button_EBK = ExcelData.get("Master_Tab_Single_Filling_Button_EBK");
	public static String EVC_RefNo = ExcelData.get("EVC_RefNo");
	public static String EVC_BookNo = ExcelData.get("EVC_BookNo");
	public static String EVC_BLNo = ExcelData.get("EVC_BLNo");
	
	public static String Booking_Module_Navigate_Button = ExcelData.get("Booking_Module_Navigate_Button");
	public static String Header_Mismatch_Popup = ExcelData.get("Header_Mismatch_Popup");
	public static String Header_Mismatch_Popup_Cancel_Button = ExcelData.get("Header_Mismatch_Popup_Cancel_Button");
	public static String Header_Mismatch_Popup_Yes_Button = ExcelData.get("Header_Mismatch_Popup_Yes_Button");
	public static String Ecomm_Validator_Header_Tab = ExcelData.get("Ecomm_Validator_Header_Tab");
	public static String Vessel_Details_TextArea = ExcelData.get("Vessel_Details_TextArea");
	public static String POL_Value_Ecom = ExcelData.get("POL_Value_Ecom");
	public static String POD_Value_Ecom = ExcelData.get("POD_Value_Ecom");
//	public static String EVC_BLNo = ExcelData.get("EVC_BLNo");

	

}
