package locators;

import java.util.Map;

import commonMethods.Testcases;
import commonMethods.Utils;

public interface Invoice_Locators{

	Map<String, String> ExcelData = Utils.getDataAsMap(Testcases.conection_vale, "Invoice", "Reference_Name",
			Testcases.environmentName);
	public static String invoice_Mode = ExcelData.get("invoice_Mode");
	public static String by_Select_Option = ExcelData.get("by_Select_Option");
	public static String customer_Search_Button = ExcelData.get("customer_Search_Button");
	public static String bl_Search_Button = ExcelData.get("bl_Search_Button");
	public static String invoice_Service_Text_Field = ExcelData.get("invoice_Service_Text_Field");
	public static String invoice_Show_BL_Button = ExcelData.get("invoice_Show_BL_Button");
	public static String invoice_Customer_Text_Field = ExcelData.get("invoice_Customer_Text_Field");
	public static String invoice_Addtional_Charges_Tab = ExcelData.get("invoice_Addtional_Charges_Tab");
	public static String invoice_Charge_Search_Button = ExcelData.get("invoice_Charge_Search_Button");
	public static String invoice_Currency_Roe_Search_Button = ExcelData.get("invoice_Currency_Roe_Search_Button");
	public static String invoice_Base_Rate_Search_Button = ExcelData.get("invoice_Base_Rate_Search_Button");
	public static String invoice_Quantity_Text_Field = ExcelData.get("invoice_Quantity_Text_Field");
	public static String invoice_Rate_Text_Field = ExcelData.get("invoice_Rate_Text_Field");
	public static String invoice_Container_Search_Button = ExcelData.get("invoice_Container_Search_Button");
	public static String invoice_Remarks_Text_Field = ExcelData.get("invoice_Remarks_Text_Field");
	public static String invoice_Addtinal_Charges_Add_Button = ExcelData.get("invoice_Addtinal_Charges_Add_Button");
	public static String invoice_Table_Headers = ExcelData.get("invoice_Table_Headers");
	public static String invoice_Table_Rows = ExcelData.get("invoice_Table_Rows");
	public static String import_invoice_dp_select = ExcelData.get("import_invoice_dp_select");
	public static String Total_count = ExcelData.get("Total_count");
	public static String Download_Excel_Xlsx = ExcelData.get("Download_Excel_Xlsx");
	public static String FilterOption_Menu = ExcelData.get("FilterOption_Menu");
	public static String Import_Invoice_girs_size = ExcelData.get("Import_Invoice_girs_size");
	public static String Import_Invoice_tab_size = ExcelData.get("Import_Invoice_tab_size");
	public static String Invoice_tab_size = ExcelData.get("Invoice_tab_size");
	public static String Import_Invoice_tabs = ExcelData.get("Import_Invoice_tabs");
	public static String report_type_cd = ExcelData.get("report_type_cd");
	public static String shipment_type_cd = ExcelData.get("shipment_type_cd");
	public static String reportType_Dropdown = ExcelData.get("reportType_Dropdown");
	public static String reportType_Dropdown_Options = ExcelData.get("reportType_Dropdown_Options");
	public static String CDP_shipment_Dropdown = ExcelData.get("CDP_shipment_Dropdown");
	public static String shipment_Dropdown_Options = ExcelData.get("shipment_Dropdown_Options");
	public static String chargeCategory_Dropdown = ExcelData.get("chargeCategory_Dropdown");
	public static String chargeCategory_Dropdown_Options = ExcelData.get("chargeCategory_Dropdown_Options");
	public static String chargeType_Dropdown = ExcelData.get("chargeType_Dropdown");
	public static String chargeType_Dropdown_Options = ExcelData.get("chargeType_Dropdown_Options");
	public static String scope_Dropdown = ExcelData.get("scope_Dropdown");
	public static String scope_Dropdown_Options = ExcelData.get("scope_Dropdown_Options");
	public static String fromDate_CDR = ExcelData.get("fromDate_CDR");
	public static String toDate_CDR = ExcelData.get("toDate_CDR");
	public static String both_RadioButton_CDR = ExcelData.get("both_RadioButton_CDR");
	public static String collect_RadioButton_CDR = ExcelData.get("collect_RadioButton_CDR");
	public static String outstanding_RadioButton_CDR = ExcelData.get("outstanding_RadioButton_CDR");
	public static String exclude_Reversal_Checkbox = ExcelData.get("exclude_Reversal_Checkbox");
	public static String supress_ZeroAmount = ExcelData.get("supress_ZeroAmount");
	public static String scope_Remove_Button = ExcelData.get("scope_Remove_Button");
	public static String scope_Add_Button = ExcelData.get("scope_Add_Button");
	public static String show_Button_CDR = ExcelData.get("show_Button_CDR");
	public static String totalRecords_CDR = ExcelData.get("totalRecords_CDR");
	public static String table_Results = ExcelData.get("table_Results");
	public static String export_search = ExcelData.get("export_search");
	public static String eport_dp = ExcelData.get("eport_dp");
	public static String eport_number = ExcelData.get("eport_number");
	public static String eport_service = ExcelData.get("eport_service");
	public static String cd_filter = ExcelData.get("cd_filter");
	public static String cd_filter_inside = ExcelData.get("cd_filter_inside");
	public static String bl_number_input = ExcelData.get("bl_number_input");
	public static String import_invoice_inv_text = ExcelData.get("import_invoice_inv_text");
	public static String invoice_inv_text = ExcelData.get("invoice_inv_text");
	public static String invoice_pop = ExcelData.get("invoice_pop");
	public static String import_invoice_dp = ExcelData.get("import_invoice_dp");
	public static String import_invoice_Tabs = ExcelData.get("import_invoice_Tabs");
	public static String HBL_Number = ExcelData.get("HBL_Number");
	public static String INV_Number = ExcelData.get("INV_Number");
	public static String INV_Currency = ExcelData.get("INV_Currency");
	public static String INV_ROE = ExcelData.get("INV_ROE");
	public static String INV_Date = ExcelData.get("INV_Date");
	public static String Party_Codes = ExcelData.get("Party_Codes");
	public static String Export_Invoice_girs_size = ExcelData.get("Export_Invoice_girs_size");
	public static String invoice_Tabs = ExcelData.get("invoice_Tabs");
	public static String Invoice_gird_size = ExcelData.get("Invoice_gird_size");
	public static String Report_Columnfilter = ExcelData.get("Report_Columnfilter");
	public static String ReportDeselect_all = ExcelData.get("ReportDeselect_all");
	public static String Column_input = ExcelData.get("Column_input");
	public static String InvoiceBound = ExcelData.get("InvoiceBound");
	public static String DropDown_Select = ExcelData.get("DropDown_Select");
	public static String POL_PortTerminal_Input = ExcelData.get("POL_PortTerminal_Input");
	public static String POL_PortCode_Input = ExcelData.get("POL_PortCode_Input");
	public static String HBL_Input = ExcelData.get("HBL_Input");
	public static String Invoice_input = ExcelData.get("Invoice_input");
	public static String BL_Row1 = ExcelData.get("BL_Row1");
	public static String Invoice_currency = ExcelData.get("Invoice_currency");
	public static String invroe = ExcelData.get("invroe");
	public static String invType = ExcelData.get("invType");
	public static String partyCode_grid = ExcelData.get("partyCode_grid");
	public static String By_BL_NumberBtn_All = ExcelData.get("By_BL_NumberBtn_All");
	public static String By_Vessel_Button_All = ExcelData.get("By_Vessel_Button_All");
	public static String By_Book_Button_All = ExcelData.get("By_Book_Button_All");
	public static String Actual_Cust_All = ExcelData.get("Actual_Cust_All");
	public static String Vessel_input = ExcelData.get("Vessel_input");
	public static String Service_input = ExcelData.get("Service_input");
	public static String InvoiceVoyage_input = ExcelData.get("InvoiceVoyage_input");
	public static String InvoicePOL = ExcelData.get("InvoicePOL");
	public static String InvoicePOD = ExcelData.get("InvoicePOD");
	public static String Vertical_Scroll = ExcelData.get("Vertical_Scroll");
	public static String Export_invoice_Tabs = ExcelData.get("Export_invoice_Tabs");
	public static String Detail_tabs = ExcelData.get("Detail_tabs");
	public static String panel_select_receipt = ExcelData.get("panel_select_receipt");
	public static String payAt_Field = ExcelData.get("payAt_Field");
	public static String payAt_Option = ExcelData.get("payAt_Option");
	public static String invoice_And_Receipt_Table_Rows = ExcelData.get("invoice_And_Receipt_Table_Rows");
	public static String invoice_And_Receipt_Column = ExcelData.get("invoice_And_Receipt_Column");
	public static String receipt_Remove_Button = ExcelData.get("receipt_Remove_Button");
	public static String match_Button = ExcelData.get("match_Button");
	public static String receipt_Show_Button = ExcelData.get("receipt_Show_Button");
	public static String receipt_Mode_Button = ExcelData.get("receipt_Mode_Button");
	public static String panel_First_Click = ExcelData.get("panel_First_Click");
	public static String Issued_Button_Invoice = ExcelData.get("Issued_Button_Invoice");
	public static String PrivilegeCode_SelectButton = ExcelData.get("PrivilegeCode_SelectButton");
	public static String pld_Agency_Text_Invoice = ExcelData.get("pld_Agency_Text_Invoice");
	public static String Agency_text_Field_Ports = ExcelData.get("Agency_text_Field_Ports");
	public static String Invoice_Table_Header_All = ExcelData.get("Invoice_Table_Header_All");
	public static String Invoice_Table_Row_All = ExcelData.get("Invoice_Table_Row_All");
	public static String In_Show_BL_Button = ExcelData.get("In_Show_BL_Button");
	public static String In_bl_Search_Button = ExcelData.get("In_bl_Search_Button");
	public static String In_by_Select_Option = ExcelData.get("In_by_Select_Option");
	public static String In_customer_Search_Button = ExcelData.get("In_customer_Search_Button");
	public static String In_reportType_Dropdown = ExcelData.get("In_reportType_Dropdown");
	public static String In_reportType_Dropdown_Options = ExcelData.get("In_reportType_Dropdown_Options");
	public static String In_Issued_Button = ExcelData.get("In_Issued_Button");
	public static String Radio_Buttons_CDR = ExcelData.get("Radio_Buttons_CDR");
	public static String Charge_Details_Report_Table = ExcelData.get("Charge_Details_Report_Table");
	public static String Amount_Column_ChargeDetailsReport = ExcelData.get("Amount_Column_ChargeDetailsReport");
	public static String Corporate_Option_AgencyROE = ExcelData.get("Corporate_Option_AgencyROE");
	
	public static String Invoice_Tabs_Headers = ExcelData.get("Invoice_Tabs_Headers");
	public static String Invoice_Table_Grid_Rows = ExcelData.get("Invoice_Table_Grid_Rows");
	
	public static String POD_Input_invoice = ExcelData.get("POD_Input_invoice");

	
}
