package locators;

import java.util.Map;

import commonMethods.Testcases;
import commonMethods.Utils;

public interface Payable_Payment_Locators {
	Map<String, String> ExcelData = Utils.getDataAsMap(Testcases.conection_vale, "Payable_Payment",
			"Reference_Name", Testcases.environmentName);

	public static String payablePayment_Module = ExcelData.get("payablePayment_Module");
	public static String paymentDate_PPT = ExcelData.get("paymentDate_PPT");
	public static String Select_Transaction_PPT = ExcelData.get("Select_Transaction_PPT");
	public static String Payment_No_TF_PPT = ExcelData.get("Payment_No_TF_PPT");
	public static String openPeriod_PPT = ExcelData.get("openPeriod_PPT");
	public static String vendor_Textfield_PPT = ExcelData.get("vendor_Textfield_PPT");
	public static String vendor_SearchButton_PPT = ExcelData.get("vendor_SearchButton_PPT");
	public static String getDetails_Button_PPT = ExcelData.get("getDetails_Button_PPT");
	public static String save_Btn_PPT = ExcelData.get("save_Btn_PPT");
	public static String show_Invoice_Btn_PPT = ExcelData.get("show_Invoice_Btn_PPT");
	public static String chequeTT_No_Txtfld_PPT = ExcelData.get("chequeTT_No_Txtfld_PPT");
	public static String deposit_Ac_Search_Btn_PPT = ExcelData.get("deposit_Ac_Search_Btn_PPT");
	public static String account_Name_Txtfld_PPT = ExcelData.get("account_Name_Txtfld_PPT");
	public static String add_Symbol_PPT = ExcelData.get("add_Symbol_PPT");
	public static String description_Txtfld_PPT = ExcelData.get("description_Txtfld_PPT");
	public static String vendorcode_Txtfld_PPT = ExcelData.get("vendorcode_Txtfld_PPT");
	public static String cash_Bank_Details_Tab_PPT = ExcelData.get("cash_Bank_Details_Tab_PPT");
	public static String payAmount_GridCell_PPT = ExcelData.get("payAmount_GridCell_PPT");
	public static String scroll = ExcelData.get("scroll");
	public static String grid_Trans_No_LRO = ExcelData.get("grid_Trans_No_LRO");
	public static String select_Checkbox_PPT = ExcelData.get("select_Checkbox_PPT");
	public static String Edit_Button_PPT = ExcelData.get("Edit_Button_PPT");
	public static String Trans_Date_Check_Box_PPT = ExcelData.get("Trans_Date_Check_Box_PPT");
	public static String trans_No_Checkbox_PPT = ExcelData.get("trans_No_Checkbox_PPT");
	public static String Currency_Check_Box_PPT = ExcelData.get("Currency_Check_Box_PPT");
	public static String transDate_Checkbox_PPT = ExcelData.get("transDate_Checkbox_PPT");
	public static String currency_Checkbox_PPT = ExcelData.get("currency_Checkbox_PPT");
	public static String currency_Select_Option_PPT = ExcelData.get("currency_Select_Option_PPT");
	public static String transNumber_Checkbox_PPT = ExcelData.get("transNumber_Checkbox_PPT");
	public static String amountRange_Checkbox_PPT = ExcelData.get("amountRange_Checkbox_PPT");
	public static String Trans_No_From_Date_PPT = ExcelData.get("Trans_No_From_Date_PPT");
	public static String Trans_No_To_Date_PPT = ExcelData.get("Trans_No_To_Date_PPT");
	public static String currency_Drpdwn_PPT = ExcelData.get("currency_Drpdwn_PPT");
	public static String trans_FromDate_PPT = ExcelData.get("trans_FromDate_PPT");
	public static String trans_ToDate_PPT = ExcelData.get("trans_ToDate_PPT");
	public static String amountRange_To_Textfield_PPT = ExcelData.get("amountRange_To_Textfield_PPT");
	public static String amountRange_From_Textfield_PPT = ExcelData.get("amountRange_From_Textfield_PPT");
	public static String cheque_Drpdwn_Label_PPT = ExcelData.get("cheque_Drpdwn_Label_PPT");
	public static String cheque_Drpdwn_Items_PPT = ExcelData.get("cheque_Drpdwn_Items_PPT");
	public static String cheque_Drpdwn_Option_PPT = ExcelData.get("cheque_Drpdwn_Option_PPT");
	public static String bank_Txtfld1_PPT = ExcelData.get("bank_Txtfld1_PPT");
	public static String bank_Txtfld2_PPT = ExcelData.get("bank_Txtfld2_PPT");
	public static String cheque_Cash_TT_Dropdown_PPT = ExcelData.get("cheque_Cash_TT_Dropdown_PPT");
	public static String date_Cash_Bank_Details_PPT = ExcelData.get("date_Cash_Bank_Details_PPT");
	public static String currency_Search_Icon_PPT = ExcelData.get("currency_Search_Icon_PPT");
	public static String currency_Code_Txtfld_PPT = ExcelData.get("currency_Code_Txtfld_PPT");
	public static String vendor_textield_PPT = ExcelData.get("vendor_textield_PPT");
	public static String vendorCode_Filter = ExcelData.get("vendorCode_Filter");
	public static String description_TextArea_PPT = ExcelData.get("description_TextArea_PPT");
	public static String transNumber_No_Checkbox_PPT = ExcelData.get("transNumber_No_Checkbox_PPT");
	public static String currency_Select_Dropdown_PPT = ExcelData.get("currency_Select_Dropdown_PPT");
	public static String cheque_Cash_TT_Option_PPT = ExcelData.get("cheque_Cash_TT_Option_PPT");
	public static String cheque_TT_No_Textfield_PPT = ExcelData.get("cheque_TT_No_Textfield_PPT");
	public static String Date_select = ExcelData.get("Date_select");
	public static String currencyCode_Filter_PPT = ExcelData.get("currencyCode_Filter_PPT");
	public static String documentAmount_Textfield_RR = ExcelData.get("documentAmount_Textfield_RR");
	public static String bank_Charges_Textfield_PPT = ExcelData.get("bank_Charges_Textfield_PPT");
	public static String bankCharges_SearchButton_PPT = ExcelData.get("bankCharges_SearchButton_PPT");
	public static String acccountName_Filter = ExcelData.get("acccountName_Filter");
	public static String acccountHead_Filter = ExcelData.get("acccountHead_Filter");
	public static String roe_Differencfe_Textfield_PPT = ExcelData.get("roe_Differencfe_Textfield_PPT");
	public static String roe_Difference_SearchButton_PPT = ExcelData.get("roe_Difference_SearchButton_PPT");
	public static String payment_AC_SearchButton_PPT = ExcelData.get("payment_AC_SearchButton_PPT");
	public static String add_Button_Cash_Bank_Details_PPT = ExcelData.get("add_Button_Cash_Bank_Details_PPT");
	public static String payAmount_GridCell_Edit_PPT = ExcelData.get("payAmount_GridCell_Edit_PPT");
	public static String totalAmount_GridCell_PPT = ExcelData.get("totalAmount_GridCell_PPT");
	public static String transNumber_Filter_PPT = ExcelData.get("transNumber_Filter_PPT");
	public static String condition_Filter_PPT = ExcelData.get("condition_Filter_PPT");
	public static String select_Option = ExcelData.get("select_Option");
	public static String scroll_PPT = ExcelData.get("scroll_PPT");
	public static String paymentNumber_Textfield_PPT = ExcelData.get("paymentNumber_Textfield_PPT");
	public static String payment_Date_PPT = ExcelData.get("payment_Date_PPT");
	public static String open_Period_PPT = ExcelData.get("open_Period_PPT");
	public static String trans_No_Checkboc_PPT = ExcelData.get("trans_No_Checkboc_PPT");
	public static String customer_Searchfield_PPT = ExcelData.get("customer_Searchfield_PPT");
	public static String customer_SearchButton_PPT = ExcelData.get("customer_SearchButton_PPT");
	public static String Vendor_Code_TF_PPT = ExcelData.get("Vendor_Code_TF_PPT");
	public static String vendor_Name_TF_PPT = ExcelData.get("vendor_Name_TF_PPT");
	public static String select_Vendor_PPT = ExcelData.get("select_Vendor_PPT");
	public static String currency_Select_PPT = ExcelData.get("currency_Select_PPT");
	public static String paymentAC_SearchButton_PPT = ExcelData.get("paymentAC_SearchButton_PPT");
	public static String acccountName_Filter_PPT = ExcelData.get("acccountName_Filter_PPT");
	public static String acccountHead_Filter_PPT = ExcelData.get("acccountHead_Filter_PPT");
	public static String Add_Button_PPT = ExcelData.get("Add_Button_PPT");
	public static String Table_PPT = ExcelData.get("Table_PPT");
	public static String financial_Year_TF = ExcelData.get("financial_Year_TF");
	public static String balance_Amount_PPT = ExcelData.get("balance_Amount_PPT");
	public static String post_Tab_Grid_Header = ExcelData.get("post_Tab_Grid_Header");
	public static String post_Tab_Grid_Row = ExcelData.get("post_Tab_Grid_Row");
	public static String Activity_Date_LRO = ExcelData.get("Activity_Date_LRO");
	public static String From_Date_LRO = ExcelData.get("From_Date_LRO");
	public static String To_Date_LRO = ExcelData.get("To_Date_LRO");
	public static String nominal_Plus_Button_LRO = ExcelData.get("nominal_Plus_Button_LRO");
	public static String nominal_Name_TF_LRO = ExcelData.get("nominal_Name_TF_LRO");
	public static String Select_Nomoinal_LRO = ExcelData.get("Select_Nomoinal_LRO");
	public static String Select_Button_LRO = ExcelData.get("Select_Button_LRO");
	public static String show_Button_LRO = ExcelData.get("show_Button_LRO");
	public static String tool_Pannel_LRO = ExcelData.get("tool_Pannel_LRO");
	public static String condition_Filter_LRO = ExcelData.get("condition_Filter_LRO");
	public static String transaction_No_LRO = ExcelData.get("transaction_No_LRO");
	public static String Profile_Dropdown = ExcelData.get("Profile_Dropdown");
	public static String Corporate_Profile = ExcelData.get("Corporate_Profile");
	public static String Location_Profile = ExcelData.get("Location_Profile");
	public static String Module_Select = ExcelData.get("Module_Select");
	public static String reset_Profile_Button = ExcelData.get("reset_Profile_Button");
	public static String Gridselect = ExcelData.get("Gridselect");
	public static String panel_First_Row = ExcelData.get("panel_First_Row");
	public static String select_button_pp = ExcelData.get("select_button_pp");
	public static String post_Button_PPT = ExcelData.get("post_Button_PPT");
	public static String filter_Icon_PPT = ExcelData.get("filter_Icon_PPT");
	public static String post_Tab_PPT = ExcelData.get("post_Tab_PPT");
	public static String currency_SearcButton_PPT = ExcelData.get("currency_SearcButton_PPT");
	public static String Select_Checkbox_AGGrid_PPT = ExcelData.get("Select_Checkbox_AGGrid_PPT");
	public static String PP_Vendor_Option = ExcelData.get("PP_Vendor_Option");
	public static String PP_Vendor_Radio_Button = ExcelData.get("PP_Vendor_Radio_Button");

}
