package locators;

import java.util.Map;

import commonMethods.Testcases;
import commonMethods.Utils;

public interface Receivable_Receipt_Locators{
	Map<String, String> ExcelData = Utils.getDataAsMap(Testcases.conection_vale, "Receivable_Receipt",
			"Reference_Name", Testcases.environmentName);

	public static String RR_Receipt_Date = ExcelData.get("RR_Receipt_Date");
	public static String RR_Open_Period = ExcelData.get("RR_Open_Period");
	public static String RR_Customer_Search = ExcelData.get("RR_Customer_Search");
	public static String RR_Customer_Text_Field = ExcelData.get("RR_Customer_Text_Field");
	public static String RR_Select_Option = ExcelData.get("RR_Select_Option");
	public static String RR_Customer_Name_Filter = ExcelData.get("RR_Customer_Name_Filter");
	public static String RR_Get_Details_Button = ExcelData.get("RR_Get_Details_Button");
	public static String RR_Show_Invoice_Button = ExcelData.get("RR_Show_Invoice_Button");
	public static String RR_Trans_Date_Check_Box = ExcelData.get("RR_Trans_Date_Check_Box");
	public static String RR_Currency_Check_Box = ExcelData.get("RR_Currency_Check_Box");
	public static String RR_Trans_No_Check_Box = ExcelData.get("RR_Trans_No_Check_Box");
	public static String RR_Amount_Range_Check_Box = ExcelData.get("RR_Amount_Range_Check_Box");
	public static String RR_Trans_From_Date = ExcelData.get("RR_Trans_From_Date");
	public static String RR_Trans_To_Date = ExcelData.get("RR_Trans_To_Date");
	public static String RR_Currency_Select = ExcelData.get("RR_Currency_Select");
	public static String RR_Currency_Select_Option = ExcelData.get("RR_Currency_Select_Option");
	public static String RR_From_Trans_No = ExcelData.get("RR_From_Trans_No");
	public static String RR_To_Trans_No = ExcelData.get("RR_To_Trans_No");
	public static String RR_From_Amount_Range = ExcelData.get("RR_From_Amount_Range");
	public static String RR_To_Amount_Range = ExcelData.get("RR_To_Amount_Range");
	public static String RR_Select_Trans_Number_Check_Box = ExcelData.get("RR_Select_Trans_Number_Check_Box");
	public static String RR_Invoice_Table_Headers = ExcelData.get("RR_Invoice_Table_Headers");
	public static String RR_Invoice_Table_Rows = ExcelData.get("RR_Invoice_Table_Rows");
	public static String cheque_Cash_TT_Option_RR = ExcelData.get("cheque_Cash_TT_Option_RR");
	public static String receivable_Receipt_Module_RR = ExcelData.get("receivable_Receipt_Module_RR");
	public static String bank_Charges_Textfield_RR = ExcelData.get("bank_Charges_Textfield_RR");
	public static String roe_Differencfe_Textfield_RR = ExcelData.get("roe_Differencfe_Textfield_RR");
	public static String roe_Difference_SearchButton_RR = ExcelData.get("roe_Difference_SearchButton_RR");
	public static String Balance_Amount = ExcelData.get("Balance_Amount");
	public static String invoice_Select_CheckBox_RR = ExcelData.get("invoice_Select_CheckBox_RR");
	public static String cheque_TT_No_Textfield_RR = ExcelData.get("cheque_TT_No_Textfield_RR");
	public static String depositAC_SearchButton_RR = ExcelData.get("depositAC_SearchButton_RR");
	public static String acccountName_Filter_RR = ExcelData.get("acccountName_Filter_RR");
	public static String acccountHead_Filter_RR = ExcelData.get("acccountHead_Filter_RR");
	public static String bankCode_Filter_RR = ExcelData.get("bankCode_Filter_RR");
	public static String bankName_Filter_RR = ExcelData.get("bankName_Filter_RR");
	public static String currencyCode_Filter_RR = ExcelData.get("currencyCode_Filter_RR");
	public static String localAmount_Textfield_RR = ExcelData.get("localAmount_Textfield_RR");
	public static String add_Button_Cash_Bank_Details_RR = ExcelData.get("add_Button_Cash_Bank_Details_RR");
	public static String date_Cash_Bank_Details_RR = ExcelData.get("date_Cash_Bank_Details_RR");
	public static String cheque_Cash_TT_Dropdown_RR = ExcelData.get("cheque_Cash_TT_Dropdown_RR");
	public static String cheque_Cash_TT_Option = ExcelData.get("cheque_Cash_TT_Option");
	public static String Descriction_Area_RR = ExcelData.get("Descriction_Area_RR");
	public static String post_Tab_Rr = ExcelData.get("post_Tab_Rr");
	public static String post_Btn_Rr = ExcelData.get("post_Btn_Rr");
	public static String bankCharges_SsearchButton_RR = ExcelData.get("bankCharges_SsearchButton_RR");
	public static String description_Txtfld_Rr = ExcelData.get("description_Txtfld_Rr");
	public static String Total_Amount_RR = ExcelData.get("Total_Amount_RR");
	public static String Select_Nominal_RR = ExcelData.get("Select_Nominal_RR");
	public static String Invoice_Amount_Edit2 = ExcelData.get("Invoice_Amount_Edit2");
	public static String Invoice_Amount_Edit1 = ExcelData.get("Invoice_Amount_Edit1");
	public static String RR_Reciept_Date = ExcelData.get("RR_Reciept_Date");
	public static String CustomerCode_Filter_RR = ExcelData.get("CustomerCode_Filter_RR");
	public static String Customer_search_Popup = ExcelData.get("Customer_search_Popup");
	public static String Total_USD_TF = ExcelData.get("Total_USD_TF");
	public static String RR_Customer_Code_Text_Field = ExcelData.get("RR_Customer_Code_Text_Field");
	public static String RR_Panel_First_Click = ExcelData.get("RR_Panel_First_Click");
	public static String get_Details_Btn_Rr = ExcelData.get("get_Details_Btn_Rr");
	public static String show_Invoice_Btn_Rr = ExcelData.get("show_Invoice_Btn_Rr");
	public static String invoice_Select_CheckBox = ExcelData.get("invoice_Select_CheckBox");
	public static String cash_Bank_Detail_Tab_Rr = ExcelData.get("cash_Bank_Detail_Tab_Rr");
	public static String cheque_Drpdwn_Rr = ExcelData.get("cheque_Drpdwn_Rr");
	public static String cheque_Drpdwn_Option_Rr = ExcelData.get("cheque_Drpdwn_Option_Rr");
	public static String cheque_Drpdwn_Iterate_Rr = ExcelData.get("cheque_Drpdwn_Iterate_Rr");
	public static String chequeTT_No_Txtfld_Rr = ExcelData.get("chequeTT_No_Txtfld_Rr");
	public static String deposit_Ac_Search_Btn_Rr = ExcelData.get("deposit_Ac_Search_Btn_Rr");
	public static String account_Head_Txtfld_Rr = ExcelData.get("account_Head_Txtfld_Rr");
	public static String panel_First_Click_Rr = ExcelData.get("panel_First_Click_Rr");
	public static String bank_Search_Btn_Rr = ExcelData.get("bank_Search_Btn_Rr");
	public static String bank_Code_Txtfld_Rr = ExcelData.get("bank_Code_Txtfld_Rr");
	public static String add_Symbol_Rr = ExcelData.get("add_Symbol_Rr");
	public static String cheque_Drpdwn_Items_Rr = ExcelData.get("cheque_Drpdwn_Items_Rr");
	public static String edit_Btn_RR = ExcelData.get("edit_Btn_RR");
	public static String roe_Cash_Bank_Tab_RR = ExcelData.get("roe_Cash_Bank_Tab_RR");
	public static String roe_Cell_Roe = ExcelData.get("roe_Cell_Roe");
	public static String roe_date_Txtfld_Tr = ExcelData.get("roe_date_Txtfld_Tr");
	public static String roe_Table_Header_Tr = ExcelData.get("roe_Table_Header_Tr");
	public static String roe_Table_Rows_Tr = ExcelData.get("roe_Table_Rows_Tr");
	public static String bank_SearchButton_RR = ExcelData.get("bank_SearchButton_RR");
	public static String Invoice_Tab_RR = ExcelData.get("Invoice_Tab_RR");
	public static String currency_SearcButton_RR = ExcelData.get("currency_SearcButton_RR");
	public static String currency_Code_Txtfld_Roe = ExcelData.get("currency_Code_Txtfld_Roe");
	public static String last_Record_Btn_RR = ExcelData.get("last_Record_Btn_RR");
	public static String cash_Bank_Details_Tab_RR = ExcelData.get("cash_Bank_Details_Tab_RR");
	public static String RR_Customer_Code = ExcelData.get("RR_Customer_Code");
	public static String RR_Grid_Table = ExcelData.get("RR_Grid_Table");
	public static String RR_Table_Scroll = ExcelData.get("RR_Table_Scroll");
	public static String RR_main_Filter = ExcelData.get("RR_main_Filter");
	public static String RR_TransNumber_Input = ExcelData.get("RR_TransNumber_Input");
	public static String RR_Grid_table_Loc = ExcelData.get("RR_Grid_table_Loc");
	public static String Select_Checkbox_AGGrid_RR = ExcelData.get("Select_Checkbox_AGGrid_RR");
	public static String RR_Header_name = ExcelData.get("RR_Header_name");

}
